/**
 * パネルを PNG / HTML として保存する導線（#500 / #505）。
 *
 * - `PanelExportButton` … パネルのヘッダに置く保存ボタン。押すと形式メニュー → 保存ダイアログ。
 * - `PanelExportCaption` … 書き出しにだけ入る「タイトル下の絞り込み条件」ブロック。
 * - `PanelExportLogo`   … 書き出しにだけ入る右上の splabo ロゴと右下のクレジット。
 *   画面では非表示（`.is-exporting` のときだけ表示）なので、通常のレイアウトは変わらない。
 *   クレジット本文（版・日付）は保存直前に `savePanel*` が埋める。
 */
import { useEffect, useRef, useState, type RefObject } from 'react'
import { EXPORT_HIDE_CLASS, savePanel, type PanelExportFormat } from '../utils/panelExport'

interface ButtonProps {
  /** キャプチャ対象（パネルの外枠）。 */
  targetRef: RefObject<HTMLElement | null>
  /** ファイル名に入る画面名。例: 'ダッシュボード' */
  screen: string
  /** ファイル名に入るパネル名。例: '武器別 バトル数 & 勝率' */
  panel: string
}

export function PanelExportButton({ targetRef, screen, panel }: ButtonProps) {
  const [busy, setBusy] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const wrapRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!menuOpen) return
    const onDoc = (e: MouseEvent) => {
      if (wrapRef.current && !wrapRef.current.contains(e.target as Node)) {
        setMenuOpen(false)
      }
    }
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setMenuOpen(false)
    }
    document.addEventListener('mousedown', onDoc)
    document.addEventListener('keydown', onKey)
    return () => {
      document.removeEventListener('mousedown', onDoc)
      document.removeEventListener('keydown', onKey)
    }
  }, [menuOpen])

  async function runSave(format: PanelExportFormat) {
    const node = targetRef.current
    if (!node || busy) return
    setMenuOpen(false)
    setBusy(true)
    try {
      await savePanel(node, screen, panel, format)
    } catch (e) {
      console.error('[PanelExport] パネルの保存に失敗:', e)
      window.alert(`パネルの保存に失敗しました。\n${String(e)}`)
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className={`panel-export-wrap ${EXPORT_HIDE_CLASS}`} ref={wrapRef}>
      <button
        type="button"
        className="panel-export-btn"
        onClick={() => {
          if (busy) return
          setMenuOpen(open => !open)
        }}
        disabled={busy}
        aria-label="パネルを保存"
        aria-haspopup="menu"
        aria-expanded={menuOpen}
        title="このパネルを PNG または HTML で保存"
      >
        {busy ? <span className="panel-export-btn__spinner" /> : <DownloadIcon />}
      </button>
      {menuOpen && !busy && (
        <div className="panel-export-menu" role="menu" aria-label="保存形式">
          <button
            type="button"
            role="menuitem"
            className="panel-export-menu__item"
            onClick={() => void runSave('png')}
          >
            PNG 画像
          </button>
          <button
            type="button"
            role="menuitem"
            className="panel-export-menu__item"
            onClick={() => void runSave('html')}
          >
            HTMLファイル
          </button>
        </div>
      )}
    </div>
  )
}

function DownloadIcon() {
  return (
    <svg viewBox="0 0 16 16" width="13" height="13" aria-hidden="true" focusable="false">
      <path
        d="M8 1.5v7.6M4.8 6.3 8 9.5l3.2-3.2M2.5 11.5v1.5a1 1 0 0 0 1 1h9a1 1 0 0 0 1-1v-1.5"
        fill="none" stroke="currentColor" strokeWidth="1.4"
        strokeLinecap="round" strokeLinejoin="round"
      />
    </svg>
  )
}

/** タイトル直下に入る絞り込み条件。`describeFilters` などで作った 1 行を渡す。 */
export function PanelExportCaption({ conditions }: { conditions: string }) {
  return (
    <div className="panel-export-caption" aria-hidden="true">{conditions}</div>
  )
}

/** パネル末尾に入る短い注釈。パネル上の長文注釈をそのまま渡さないこと。 */
export function PanelExportNote({ note }: { note: string }) {
  return (
    <div className="panel-export-note" aria-hidden="true">{note}</div>
  )
}

/**
 * 書き出しに焼き込むブランディング。右上に splabo ロゴ、右下にクレジット枠。
 * クレジット文言（`Generated by SpLabo vX.Y.Z · YYYY-MM-DD`）は
 * 保存直前に `savePanel*` が `.panel-export-credit` へ書き込む。
 */
export function PanelExportLogo() {
  return (
    <>
      <img
        className="panel-export-logo"
        src="/splabo-logo.png"
        alt=""
        aria-hidden="true"
        draggable={false}
      />
      <div className="panel-export-credit" aria-hidden="true" />
    </>
  )
}
