/**
 * パネルを PNG / HTML として保存する導線（#500 / #505）。
 *
 * - `PanelExportButton` … パネルのヘッダに置く保存ボタン。押すと形式メニュー → 保存ダイアログ。
 * - `PanelExportCaption` … 書き出しにだけ入る「タイトル下の絞り込み条件」ブロック。
 * - `PanelExportLogo`   … 書き出しにだけ入る右上の splabo ロゴと右下のクレジット。
 *   画面では非表示（`.is-exporting` のときだけ表示）なので、通常のレイアウトは変わらない。
 *   クレジット本文（版・日付）は保存直前に `savePanel*` が埋める。
 */
import { useEffect, useRef, useState, type RefObject } from 'react'
import { useTranslation } from 'react-i18next'
import { EXPORT_HIDE_CLASS, savePanel, type PanelExportFormat } from '../utils/panelExport'

interface ButtonProps {
  /** キャプチャ対象（パネルの外枠）。 */
  targetRef: RefObject<HTMLElement | null>
  /** ファイル名に入る画面名。例: 'ダッシュボード' */
  screen: string
  /** ファイル名に入るパネル名。例: 'ブキ別 バトル数 & 勝率' */
  panel: string
}

export function PanelExportButton({ targetRef, screen, panel }: ButtonProps) {
  const { t } = useTranslation()
  const [busy, setBusy] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const wrapRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!menuOpen) return
    const onDoc = (e: MouseEvent) => {
      if (wrapRef.current && !wrapRef.current.contains(e.target as Node)) {
        setMenuOpen(false)
      }
    }
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setMenuOpen(false)
    }
    document.addEventListener('mousedown', onDoc)
    document.addEventListener('keydown', onKey)
    return () => {
      document.removeEventListener('mousedown', onDoc)
      document.removeEventListener('keydown', onKey)
    }
  }, [menuOpen])

  async function runSave(format: PanelExportFormat) {
    const node = targetRef.current
    if (!node || busy) return
    setMenuOpen(false)
    setBusy(true)
    try {
      await savePanel(node, screen, panel, format)
    } catch (e) {
      console.error('[PanelExport] パネルの保存に失敗:', e)
      window.alert(t('panelExport.saveFailed', { detail: String(e) }))
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className={`panel-export-wrap ${EXPORT_HIDE_CLASS}`} ref={wrapRef}>
      <button
        type="button"
        className="panel-export-btn"
        onClick={() => {
          if (busy) return
          setMenuOpen(open => !open)
        }}
        disabled={busy}
        aria-label={t('panelExport.saveAria')}
        aria-haspopup="menu"
        aria-expanded={menuOpen}
        title={t('panelExport.saveTitle')}
      >
        {busy ? <span className="panel-export-btn__spinner" /> : <DownloadIcon />}
      </button>
      {menuOpen && !busy && (
        <div className="panel-export-menu" role="menu" aria-label={t('panelExport.formatMenuAria')}>
          <button
            type="button"
            role="menuitem"
            className="panel-export-menu__item"
            onClick={() => void runSave('png')}
          >
            {t('panelExport.png')}
          </button>
          <button
            type="button"
            role="menuitem"
            className="panel-export-menu__item"
            onClick={() => void runSave('html')}
          >
            {t('panelExport.html')}
          </button>
        </div>
      )}
    </div>
  )
}

function DownloadIcon() {
  return (
    <svg viewBox="0 0 16 16" width="13" height="13" aria-hidden="true" focusable="false">
      <path
        d="M8 1.5v7.6M4.8 6.3 8 9.5l3.2-3.2M2.5 11.5v1.5a1 1 0 0 0 1 1h9a1 1 0 0 0 1-1v-1.5"
        fill="none" stroke="currentColor" strokeWidth="1.4"
        strokeLinecap="round" strokeLinejoin="round"
      />
    </svg>
  )
}

/** タイトル直下に入る絞り込み条件。`describeFilters` などで作った 1 行を渡す。 */
/** キャプションの区切り。`buildExportCaption` / `joinConditions` と揃える。 */
const CAPTION_SEP = ' / '

/**
 * 保存画像・保存 HTML に焼き込む絞り込み条件。
 *
 * 🔴 **区切りの位置でしか折り返させない。** 日本語はほぼ全ての文字間で改行できるので、
 * 素の文字列のまま置くとブラウザが幅に入るところで機械的に切る。
 * 「該当 41,566 バトル」が「…バト / ル」に割れて、**行末に 1 文字だけ残る**ことがあった。
 * 桁数や条件が変われば割れる場所も変わるので、書き方では避けられない。
 *
 * 区切りごとに `<span>` へ分けておけば、折り返しはそこだけで起きる。
 * 見た目（区切りも含めた文字列）は変わらない。
 */
export function PanelExportCaption({ conditions }: { conditions: string }) {
  const parts = conditions.split(CAPTION_SEP)
  return (
    <div className="panel-export-caption" aria-hidden="true">
      {parts.map((part, i) => (
        // 区切りは前の塊に付ける。行頭に「/」が来ないようにするため。
        <span key={i}>{i > 0 ? CAPTION_SEP : ''}{part}</span>
      ))}
    </div>
  )
}

/** パネル末尾に入る短い注釈。パネル上の長文注釈をそのまま渡さないこと。 */
export function PanelExportNote({ note }: { note: string }) {
  return (
    <div className="panel-export-note" aria-hidden="true">{note}</div>
  )
}

/**
 * 書き出しに焼き込むブランディング。右上に splabo ロゴ、右下にクレジット枠。
 * クレジット文言（`Generated by SpLabo vX.Y.Z · YYYY-MM-DD`）は
 * 保存直前に `savePanel*` が `.panel-export-credit` へ書き込む。
 */
export function PanelExportLogo() {
  return (
    <>
      <img
        className="panel-export-logo"
        src="/splabo-logo.png"
        alt=""
        aria-hidden="true"
        draggable={false}
      />
      <div className="panel-export-credit" aria-hidden="true" />
    </>
  )
}
