//! ギア（頭防具・服・靴）とブランドの公式英語名（#714 系）。
//!
//! splatoon3.ink のロケールデータ（https://splatoon3.ink/data/locale/en-US.json・
//! ja-JP.json、2026-08 時点、548 件）から生成。キーは SplatNet3 の内部 ID（16 進ハッシュ）
//! だが splabo 側にこの ID が無いため、日本語名の文字列を仲介キーにして対応付けている
//! （日本語名の重複が無いことをテストで検証済み）。
//!
//! stat.ink の /api/v1/gear は Splatoon 1/2 時代のカタログが凍結されたもので、
//! Splatoon 3 限定ブランド（バラズシ・シチリン等）を欠くため不採用（255件のみ）。
//!
//! ギアは新シーズンで追加されることがあるため、weapon_static.rs と違い陳腐化しうる。
//! 新ギア追加時は splatoon3.ink から再取得して追記する。

/// 日本語名 → 公式英語名。
pub const GEAR_NAME_EN: &[(&str, &str)] = &[
    ("イトヨリキャップ", "Bream-Brim Cap"),
    ("バイカーシェード", "Moto Shades"),
    ("バラズシ ノリマキ", "Barazushi Wrap"),
    ("ザ・ベース ルーキー", "Suede Basics"),
    ("モトクロス ソリッドブルー", "Blue Moto Boots"),
    ("タコロンT 赤", "Red Cuttlegear LS"),
    ("アナアキロンT ドライブ", "Annaki Drive Tee "),
    ("ショートビーニー", "Short Beanie"),
    ("ベリベリホワイト", "White 3-Straps"),
    ("デカロニックミント", "Cyan Dakroniks"),
    ("ヴィンテージチェック", "Vintage Check Shirt"),
    ("ピラニアモカシン", "Piranha Moccasins"),
    ("スケボーメット", "Skate Helmet"),
    ("イカスミチップ", "Squink Wingtips"),
    ("シカイバイザー", "Lo-Vis Visor"),
    ("ジェットキャップ", "Jet Cap"),
    ("サンサンサンバイザー", "Sun Visor"),
    ("アロメスローガンT", "Tentatek Slogan Tee"),
    ("ウミウシボルト95", "Sea Slug Volt 95s"),
    ("モーグル タタキベッチュー", "Toni Kensa Goggles"),
    ("FCジャージー", "Retro Gamer Jersey"),
    ("チドリメロンＴ", "Squid-Stitch Tee"),
    ("ショートニットカサネ", "Short Knit Layers"),
    ("ステッチシャツ ヤガラ", "Fancyfish Stitch"),
    ("バンドT SQUIDSQUAD", "Squid Squad Band Tee"),
    ("スミガードゴーグル", "Ink-Guard Goggles"),
    ("クンフーパンジャージ", "Panda Kung-Fu Zip-Up"),
    ("アローズ タタキベッチュー", "Arrow Pull-Ons"),
    ("ボーダービーニー", "Striped Beanie"),
    ("チドリキャップ", "Squid-Stitch Cap"),
    ("アロメテックT ブルー", "Blue Tentatek Tee"),
    ("ヒラメキブレインメット", "Brain Strainer"),
    ("パドリングジャケット ネガ", "Ink-Black Paddle Jack"),
    ("アーバンベスト ナイト", "Dark Urban Vest"),
    ("イカンカン", "Straw Boater"),
    ("ミミタコ8", "Ocho OctoPhones"),
    ("グリーンＴ", "Green Tee"),
    ("スプラッシュゴーグル", "Splash Goggles"),
    ("ステカセヘッドホン", "Squidlife Headphones"),
    ("ミントＴ", "Mint Tee"),
    ("カレッジスウェット グレー", "Gray College Sweat"),
    ("テッカサイクルキャップ", "Cycling Cap"),
    ("パワーストリップ アカアシ", "Red Power Stripes"),
    ("グリッチョ ブルー", "Blue Lo-Tops"),
    ("キングタコスターマスク", "Octoking Facemask"),
    ("キングオクトHKシャツ", "Octoking HK Jersey"),
    ("エギング4 アオクロ", "Blue & Black Squidkid IV"),
    ("ベリベリサン シアン", "Cyan Dadfoot Sandals"),
    ("パイロットメット", "Astro Helm"),
    ("イカボウズジェットブラック", "Inky Kid Clams"),
    ("テンヤ8 レッド", "Tenya OctoReds"),
    ("キャンバス ホワイト", "Cream Basics"),
    ("エンペーサートレーナー", "N-Pacer Sweat"),
    ("パラソルチューリップ", "Tulip Parasol"),
    ("ボーダーモスグリーン", "Green Striped LS"),
    ("レイニーモスグリーン", "Green Rain Boots"),
    ("オクタリアンレトロ", "Octarian Retro"),
    ("エンペーサーCaO", "N-Pacer CaO"),
    ("イカゴッチンベスト", "Squid-Pattern Waistcoat"),
    ("イカホワイト", "White Tee"),
    ("イカロスHKメット", "Hockey Helmet"),
    ("カジカブト", "Five-Alarm Helmet"),
    ("ノーズガードモトクロス", "Motocross Nose Guard"),
    ("ヤキフグビスケットバンダナ", "FishFry Biscuit Bandana"),
    ("ジップアップ グリーン", "Green Zip Hoodie"),
    ("ヤキフグシャワサン アカ", "Red FishFry Sandals"),
    ("キャンプキャップ", "Lightweight Cap"),
    ("エギング5 シロアカ", "Red & White Squidkid V"),
    ("デカメットアイシールド", "Deca Tackle Visor Helmet"),
    ("イカサンT", "Tri-Squid Tee"),
    ("ロングビルキャップ", "Long-Billed Cap"),
    ("イカノボリベスト", "Squidstar Waistcoat"),
    ("キャンバスHi トマト", "Red Hi-Tops"),
    ("レイニーアセロラ", "Acerola Rain Boots"),
    ("ヤコバイザー", "Takoroka Visor"),
    ("オータムネル", "Lumberjack Shirt"),
    ("ハイテクスコープ", "360 All-Scopes"),
    ("ハンティングジャケットKK", "Dusty Field Jacket"),
    ("エンペラフックHDP", "Squidfin Hook Cans"),
    ("キングオブマスク", "King Facemask"),
    ("ブロブスマイルマスク", "BlobMob Mask"),
    ("スシズメブロブ ベリー", "Berry BlobMob Tee"),
    ("MODZ-9", "E-JECT 30XX"),
    ("デカロノーレース ホワイト", "White Laceless Dakroniks"),
    ("F-3 ホワイトレザー", "White Leather F-3"),
    ("トレッキングカスタム", "Custom Trail Boots"),
    ("ベクトルパターン グレー", "Gray Vector Tee"),
    ("タイシャツ", "Shirt & Tie"),
    ("ラバーソール ホワイト", "White Kicks"),
    ("ロゴヅクシMTBメット", "MTB Helmet"),
    ("ウラスカジャン", "Zapfish Satin Jacket"),
    ("ノーリーチャッカ ロビンズ", "Suede Marine Lace-Ups"),
    ("パイロットゴーグル", "Pilot Goggles"),
    ("ナリキリハイテクスーツ", "Astro Wear"),
    ("バンドT WETFLOOR", "Wet Floor Band Tee"),
    ("ロブスターブーニー", "Safari Hat"),
    ("バトロング ホワイト", "White LS"),
    ("ナイトビジョン", "Stealth Goggles"),
    ("ヤコメッシュ", "Takoroka Mesh"),
    ("ヤコナイロンレトロ", "Takoroka Windcrusher"),
    ("ホワイトアローズ", "White Arrows"),
    ("ピンポンポロ", "Black Polo"),
    ("リールロールスウェット", "Reel Sweat"),
    ("エゾッコメッシュ", "Zekko Mesh"),
    ("イカバッテンロング", "Squidmark LS"),
    ("フグハンチング", "Blowfish Newsie"),
    ("タコツボメット", "Deep Sinker Helm"),
    ("アナアキロンT イボルブ", "Annaki Evolution Tee"),
    ("イカバケット", "Bucket Hat"),
    ("レイヤード ブラック", "Black Layered LS"),
    ("ヘッドバンド ホワイト", "White Headband"),
    ("アイスグラデT", "Icewave Tee"),
    ("ベリベリレッド", "Red 3-Straps"),
    ("アナアキニット アオソデ", "Annaki Blue Cuff"),
    ("ビバレッジキャップ", "Streetstyle Cap"),
    ("マウンテンベリー", "Berry Ski Jacket"),
    ("マルサンSV925", "SV925 Circle Shades"),
    ("ラバーソール ターコイズ", "Turquoise Kicks"),
    ("イカライダーBLACK", "Black Inky Rider"),
    ("ガーディアンズスーツ", "Commander Tunic"),
    ("ウーニーズBBシャツ", "Urchins Jersey"),
    ("ヤキフグ8bit ブラック", "Black 8-Bit FishFry"),
    ("ハンティングブーツ", "Hunting Boots"),
    ("シャツノゾキピンク", "Pink Hoodie"),
    ("ウミウシイエロー", "Neon Sea Slugs"),
    ("カナリアビーンズ", "Canary Trainers"),
    ("デカロゴＴ シロ", "White Deca Logo Tee"),
    ("イカジャマイカ", "Reggae Tee"),
    ("カレッジラグラン", "Varsity Baseball LS"),
    ("フロート クリアグラス", "Invisifloats"),
    ("イカスタンシャツ", "Rodeo Shirt"),
    ("ガーディアンズキャップ", "Commander Cap"),
    ("おどるイカアロハ", "Aloha Shirt"),
    ("キャッチャーマスクFU", "Home-Team Catcher"),
    ("ヤキフグ8bit ホワイト", "White 8-Bit FishFry"),
    ("クラゲーダーキャップ", "Jellyvader Cap"),
    ("フカヒレニマイバ", "Mako Bucket Hi-Tops"),
    ("パッチハット", "Patched Hat"),
    ("フォーリマスク デジカモ", "Digi-Camo Forge Mask"),
    ("アナアキバスクベレー", "Annaki Beret & Glasses"),
    ("スゲ", "Bamboo Hat"),
    ("ヤマビコＴ ブルー", "Blue Peaks Tee"),
    ("ボルダーシューズ タイノエ", "Sunny Climbing Shoes"),
    ("ハウスタグデニムCAP", "House-Tag Denim Cap"),
    ("ダイバーゴーグル", "Snorkel Mask"),
    ("デカロTゴールデン", "Dakro Golden Tee"),
    ("ベクトルラインガサネ", "Layered Vector LS"),
    ("レイヤード ホワイト", "White Layered LS"),
    ("マルミエールUD", "See-an-Enemy HUD"),
    ("ヤマギリビーニー", "Yamagiri Beanie"),
    ("エイズリーバンダナ", "Paisley Bandana"),
    ("アケビコンフォート", "Plum Casuals"),
    ("アローズサンダル アオキ", "Arrow Toesies Blu"),
    ("イカベーダーキャップ", "Squidvader Cap"),
    ("スタジオヘッドホン", "Studio Headphones"),
    ("タレサン18K", "18K Aviators"),
    ("キングフリップメッシュ", "King Flip Mesh"),
    ("キングオクトTミドリベロア", "Green Velour Octoking Tee"),
    ("エンペリアルNV", "Navy Enperrials"),
    ("ハイパーミライスーツ", "Retro Future Suit"),
    ("ジップアップ カモ", "Camo Zip Hoodie"),
    ("ウインターボンボン", "Sporty Bobble Hat"),
    ("ノリマキ750 ホワイト", "White Norimaki 750s"),
    ("デメニギスゴーグル", "Ink-Tinted Goggles"),
    ("ヌバックブーツ レッド", "Red Work Boots"),
    ("FCカラスミ", "Slipstream United"),
    ("アロメッシュバーミリオン", "Orange-Mesh Sneakers"),
    ("アナアキラバー ハバネロ", "Annaki Habaneros"),
    ("チョコガサネ", "Choco Layered LS"),
    ("パワーリセットHi", "Force ReBoots"),
    ("ハイパーミライヘッド", "Retro Future Helmet"),
    ("グレープＴ", "Grape Tee"),
    ("ミスターシュラッグT", "Mister Shrug Tee"),
    ("スミチラシシャツ", "Fashion Splash Shirt"),
    ("アロメッシュイエロー", "Yellow-Mesh Sneakers"),
    ("リイシューT ブラウン", "Tan Retro Tee"),
    ("イロマキ750 グリーン", "Green Iromaki 750s"),
    ("キングオクトTブラックベロア", "Black Velour Octoking Tee "),
    ("オクトメットプライズデコ", "Octo Tackle Helmet Deco"),
    ("エギング5 クロアオ", "Black & Blue Squidkid V"),
    ("ガチガサネ", "Layered Anchor LS"),
    ("カリスマシンガージャケット", "Brinestone Jacket"),
    ("トンビシールドR255", "Squidbeak Shield"),
    ("ドロップスウェット ネガ", "Negative Longcuff Sweater"),
    ("ストリップ タタキベッチュー", "Toni Kensa Black Hi-Tops"),
    ("スイミングモーグル", "Swim Goggles"),
    ("エゾッコパーカー ウグイス", "Olive Zekko Parka"),
    ("シーホース ブラックレザー", "Black Seahorses"),
    ("ガチブラック", "Black Anchor Tee"),
    ("ペインターマスク", "Painter's Mask"),
    ("トレッキングライト", "Trail Boots"),
    ("カリスマシンガーブーツ", "Brinestone Boots"),
    ("ダテコンタクト", "Fake Contacts"),
    ("クロブチ レトロ", "Retro Specs"),
    ("ゆとりボーダー ライム", "Lime Easy-Stripe Shirt"),
    ("イカセーラー ホワイト", "White Sailor Suit"),
    ("ゴマシオ270", "Sesame Salt 270s"),
    ("ロッキンチェリー", "Punk Cherries"),
    ("リンガーT パイン", "Pineapple Ringer"),
    ("ホタテンガロン", "Howdy Hat"),
    ("バンドT ABXY", "Chirpy Chips Band Tee"),
    ("マッチャ ライトダウン", "Matcha Down Jacket"),
    ("ウキアガールRB", "3D Glasses"),
    ("イカスカルマスク", "Skull Bandana"),
    ("ベリベリサン マゼンタ", "Pink Dadfoot Sandals"),
    ("アナアキスクエアグラス", "Annaki Charms"),
    ("ロッケンブレイクジャケット", "Rockin' Leather Jacket"),
    ("キャンプハット", "Camping Hat"),
    ("サファリハット", "Jungle Hat"),
    ("ボンバージャケット ポジ", "Light Bomber Jacket"),
    ("ハリキリインベンター", "Hacker Jacket"),
    ("F-190", "Forge Inkling Parka"),
    ("サイクルメット", "Bike Helmet"),
    ("レイヤードットシャツ", "Dots-on-Dots Shirt"),
    ("アスレチックアローズ", "Athletic Arrows"),
    ("フグベルハット", "Blowfish Bell Hat"),
    ("タコＴ", "Octo Tee"),
    ("オルカHi サンセット", "Sunset Orca Hi-Tops"),
    ("ランニングバンド", "Jogging Headband"),
    ("グリッチョ オレンジ", "Orange Lo-Tops"),
    ("ウミウシタウンHi アンバー", "Amber Sea Slug Hi-Tops"),
    ("クラマナスウェット", "Manatee Swag Sweat"),
    ("ローラーシューズGT", "Trevally Derby Rollers"),
    ("スミカケシャツ", "Inkfall Shirt"),
    ("スカッシュバンド", "Squash Headband"),
    ("デカロTキウイ", "Dakro Nana Tee"),
    ("デカロノーレース ブルー", "Blue Laceless Dakroniks"),
    ("モンゴウベレー", "Special-Forces Beret"),
    ("デカロニックチョコレート", "Chocolate Dakroniks"),
    ("ヤキフグ サンバイザー", "FishFry Visor"),
    ("オーロラヘッドホン", "Designer Headphones"),
    ("スリッポン レッド", "Red Slip-Ons"),
    ("フィッシャーズベスト オジ", "Fishing Vest"),
    ("エル・カラマレス", "El Rey Calamar"),
    ("ホーンメットBF", "Party Hard Hat"),
    ("フグベルベルハット", "Fugu Bell Hat"),
    ("クロヤキフグバンダナ", "Black FishFry Bandana"),
    ("ニクショクＴ", "Carnivore Tee"),
    ("グリッチョ グリーン 限定版", "LE Lo-Tops"),
    ("ヤコタイダイ レインボー", "Takoroka Rainbow Tie Dye"),
    ("ノックアウトシューズ", "Knockout Boots"),
    ("イロマキ750 ブルー", "Blue Iromaki 750s"),
    ("イカバッテンガード", "Squid Facemask"),
    ("01STER コハク", "Pearl 01STERs"),
    ("ヤマビコボーダー", "Striped Peaks LS"),
    ("エネルギッシュジャケット", "Cooler Jacket"),
    ("マウンテンチリペッパー", "Chili-Pepper Ski Jacket"),
    ("ピンクビーンズ", "Pink Trainers"),
    ("キングタンク マリン", "Navy King Tank"),
    ("フィレジャケット", "Patchwork Bomber"),
    ("パールドットＴ", "Pearl Tee"),
    ("セルブロウ", "Half-Rim Glasses"),
    ("クンフージャージ", "Kung-Fu Zip-Up"),
    ("ショーグンメット", "Octavio Dome"),
    ("バックワードキャップ", "Backward Cap"),
    ("スウェットT ゴブ", "Half-Sleeve Sweater"),
    ("フィッシャーマンキャップ", "Wharfside Cap"),
    ("オクタグラス", "Octoglasses"),
    ("スタジャンロゴマシ", "Varsity Jacket"),
    ("ドゥーラグキャップガサネ", "Do-Rag, Cap & Glasses"),
    ("ウールウーニーズクラシック", "Woolly Urchins Classic"),
    ("3Dニット シャーク", "Apex Sweater"),
    ("ブルーベリーコンフォート", "Blueberry Casuals"),
    ("イカリスウェット", "Anchor Sweat"),
    ("バイトヘルメット レプリカ", "Hard Hat Replica"),
    ("イカブラック", "Black Tee"),
    ("クレイジーアローズ", "Crazy Arrows"),
    ("キャンバスHi モロヘイヤ", "Hunter Hi-Tops"),
    ("イカライダーWHITE", "White Inky Rider"),
    ("アローバンド ホワイト", "White Arrowbands"),
    ("F-3 ペイントカスタム", "Custom Painted F-3 "),
    ("ユデスパイカ", "Soccer Shoes"),
    ("ベリベリサン オレンジ", "Orange Dadfoot Sandals"),
    ("シーホースHi レッド", "Red Hi-Horses"),
    ("アナアキT チョーカー", "Annaki Choker Tee"),
    ("アナアキラバー フェイク", "Annaki Tigers"),
    ("アローバンド ブラック", "Black Arrowbands"),
    ("アーバンベスト イエロー", "Yellow Urban Vest"),
    ("ブラックビーンズ", "Black Trainers"),
    ("ハウスタグホエールニット", "Whale-Knit Sweater"),
    ("ヒモヒモグリーン", "Green Lace-Ups"),
    ("パイレーツボーダー", "Pirate-Stripe Tee"),
    ("ヤコラグランクレイジー", "Takoroka Crazy Baseball LS"),
    ("ヤマハット", "Mountie Hat"),
    ("バスケバンド", "B-ball Headband"),
    ("シーホースHi ゾンビ", "Zombie Hi-Horses"),
    ("5パネルキャップ", "Five-Panel Cap"),
    ("コテボレロ ネガ", "Orca Bolero"),
    ("シェーディングキャップ スミ", "Ink-Black Flap Cap"),
    ("バラズシヤッケ", "Barazushi Anorak"),
    ("ダックブーツ スノウ", "Arctic Duck Boots"),
    ("2ラインメッシュ", "Two-Stripe Mesh"),
    ("シンカイレザーブーツ", "Deepsea Leather Boots"),
    ("ロゴマシマシアロハ", "Logo Aloha Shirt"),
    ("BBサンダル", "Black Flip-Flops"),
    ("イカサシ スクランブル", "U Jellys"),
    ("トレッキングプロ", "Pro Trail Boots"),
    ("ガンガゼロックT クロ", "Black Urchin Rock Tee"),
    ("リブニット", "Knitted Hat"),
    ("チャバハンティングブーツ", "Tea-Green Hunting Boots"),
    ("甲伝導エンペラEP", "Cephalo Pods"),
    ("F-010", "Forge Octarian Jacket"),
    ("スリッポン チドリ", "Squid-Stitch Slip-Ons"),
    ("マウンテンノリタマゴ", "Lemon Mountain Coat"),
    ("ピエロシャツ", "Button-Clown Shirt"),
    ("さくらエビポロ", "Shrimp-Pink Polo"),
    ("ミスターベースボール", "Baseball Jersey"),
    ("ω-3T", "ω-3 Tee"),
    ("シーホースHi パープル", "Purple Hi-Horses"),
    ("マルベッコー", "Full-Moon Glasses"),
    ("ロッキンブラック", "Punk Nights"),
    ("シェルメット", "Winkle Stripe Helm"),
    ("ホットグラデT", "Firewave Tee"),
    ("キャンバスHi マッシュルーム", "Cream Hi-Tops"),
    ("イロメガネ", "Tinted Shades"),
    ("フジツボペタサン", "Musselforge Flip-Flops"),
    ("レイニーブルーＴ", "Rainy-Day Tee"),
    ("マリンボーダー", "Sailor-Stripe Tee"),
    ("デカロゴT ノーコン", "Navy Deca Logo Tee"),
    ("シーホース ホワイト", "White Seahorses"),
    ("オルカHi", "Orca Hi-Tops"),
    ("スミヌキシャツ", "Ink-Wash Shirt"),
    ("ノーリーチャッカ トライブ", "Suede Nation Lace-Ups"),
    ("ヤコピステ", "Takoroka Jersey"),
    ("エギング4 キイコン", "Sun & Shade Squidkid IV"),
    ("アオサドーレ", "FC Albacore"),
    ("エギング4 アカクロ", "Red & Black Squidkid IV"),
    ("ロブスターズユニ", "Lob-Stars Jersey"),
    ("エギング5 ハニオレ", "Honey & Orange Squidkid V"),
    ("テニスバンド", "Tennis Headband"),
    ("アロメランベスト シルバー", "Silver Tentatek Vest"),
    ("フォーリマスク", "Forge Mask"),
    ("レトロジャッジ", "Retro Sweat"),
    ("ヌバックブーツ イエロー", "Tan Work Boots"),
    ("エンペーサーAg", "N-Pacer Ag"),
    ("イカンカン クラシック", "Classic Straw Boater"),
    ("ウミボーズ ホーム", "Umibozu Home Jersey"),
    ("チャッカブーツ サンド", "Desert Chukkas"),
    ("ボンバージャケット ネガ", "Dark Bomber Jacket"),
    ("ヒッコリーワークキャップ", "Hickory Work Cap"),
    ("ミズシュラッグT", "Missus Shrug Tee"),
    ("スリッポン ポルカ", "Polka-Dot Slip-Ons"),
    ("わかばタコT", "Fresh Octo Tee"),
    ("イカセーラー ブルー", "Blue Sailor Suit"),
    ("ホタプラントパーカー", "Hothouse Hoodie"),
    ("アイロニックレイヤード", "Zink Layered LS"),
    ("ボーラークラシック", "Classic Bowler"),
    ("タイツキベイビークラゲ", "Baby-Jelly Shirt & Tie"),
    ("イカホワイトV", "White V-Neck Tee"),
    ("ベクトルパターン レッド", "Red Vector Tee"),
    ("エンペーサーAu", "N-Pacer Au"),
    ("アナアキスパイダー6ホール", "Annaki Arachno Boots"),
    ("シーホース イエロー", "Yellow Seahorses"),
    ("オスモル アイボリー", "Cream Tundra Fleece"),
    ("ハラシロラグラン", "White Baseball LS"),
    ("イロマキ750 パープル", "Purple Iromaki 750s"),
    ("イロマキ750 オレンジ", "Orange Iromaki 750s"),
    ("デルタストラップ ルミナス", "Luminous Delta Straps"),
    ("トワイライトグラデT", "Vaporwave Tee"),
    ("イロマキ750 イエロー", "Yellow Iromaki 750s"),
    ("キャディ サンバイザー", "Golf Visor"),
    ("アイロニックロング", "Zink LS"),
    ("ボンボンニット", "Bobble Hat"),
    ("オールウェイズファン", "Airflow & Hustle Jacket"),
    ("ヤキフグ16bit ブルー", "Blue 16-Bit FishFry"),
    ("キャンバス クマノミ", "Clownfish Basics"),
    ("バラズシT ゲンマイ", "Barazushi Black Tee"),
    ("ウミウシレッド", "Red Sea Slugs"),
    ("アナアキニット キソデ", "Annaki Yellow Cuff"),
    ("ガブリエルT", "Eelzebub Tee"),
    ("カイガラスゲ", "Seashell Bamboo Hat"),
    ("マウンテンダウン", "Mountain Vest"),
    ("ヤマビコＴ アイボリー", "Ivory Peaks Tee"),
    ("ロッケンベルグＴ ブラック", "Rockenberg Black"),
    ("ピンポンバンド", "Squidband"),
    ("ノーリーチャッカ グレー", "Suede Gray Lace-Ups"),
    ("フェイスバイザー", "Face Visor"),
    ("レアスパイカ", "LE Soccer Shoes"),
    ("アナアキマスク", "Annaki Mask"),
    ("ホタパーカー ブラック", "Black Hoodie"),
    ("リイシューT ブルー", "Blue Retro Tee"),
    ("ミライスタージャケット", "SplatJack 5000"),
    ("シャークモカシン", "Shark Moccasins"),
    ("ボーダーネイビー", "Navy Striped LS"),
    ("ツヤケシMTBメット", "Matte Bike Helmet"),
    ("イカノメＴ ブラック", "Black Squideye"),
    ("NNJグリーン", "Wasabi Tabi"),
    ("リンガーT アップル", "Apple Ringer"),
    ("イカノルディック", "Squid Nordic"),
    ("アイスダウンブーツ", "Icy Down Boots"),
    ("マスクドホッコリー", "Firefin Facemask"),
    ("ステンシルデニムハット", "Jean Dream Bucket"),
    ("ゆとりボーダー ピンク", "Pink Easy-Stripe Shirt"),
    ("ロッキンホワイト", "Punk Whites"),
    ("トレジャーメット", "Treasure Hunter"),
    ("パワーストリップ アオアシ", "Blue Power Stripes"),
    ("トビウォーズHKユニ", "Inkopolis Squaps Jersey"),
    ("フライトぼう", "Pilot Hat"),
    ("カモメッシュ", "Camo Mesh"),
    ("ヤキフグシャワサン キ", "Yellow FishFry Sandals"),
    ("ロッケンベルグＴ ホワイト", "Rockenberg White"),
    ("FA-01ウラ", "FA-01 Reversed"),
    ("モンスター PCU56", "Arctic Monster Parka"),
    ("カレッジスウェット ネイビー", "Navy College Sweat"),
    ("テッカサイクルシャツ", "Cycling Shirt"),
    ("スリッポン ブルー", "Blue Slip-Ons"),
    ("パラシューター プルーン", "Prune Parashooter"),
    ("オシノビニット", "Sneaky Beanie"),
    ("シーホースHi ゴールド", "Gold Hi-Horses"),
    ("ベイビークラゲシャツ", "Baby-Jelly Shirt"),
    ("レイニーシャボン", "Bubble Rain Boots"),
    ("バンドT HIGHTIDEERA", "Hightide Era Band Tee"),
    ("スパイカ タタキベッチュー", "Toni Kensa Soccer Shoes"),
    ("タツノコキューバ", "Seahorse Shoreliner"),
    ("キャンバス バナナ", "Banana Basics"),
    ("イヤーマフ", "Noise Cancelers"),
    ("バハフーディー ロホ", "Sudadera Roja"),
    ("キングタンク スラッシュ", "Slash King Tank"),
    ("ロッキンイエロー", "Punk Yellows"),
    ("ジョーズモカシン", "Mawcasins"),
    ("トリコロールラガー", "Tricolor Rugby"),
    ("シェルバシラWO", "Slamgerine Slip-Ons"),
    ("エゾッコロンTキャロット", "Zekko Long Carrot Tee"),
    ("ピーターパンクシャツ", "Hula Punk Shirt"),
    ("アナアキアンピンベレー", "Annaki Beret"),
    ("ハラグロラグラン", "Black Baseball LS"),
    ("イカバッテン マスタード", "Squidmark Sweat"),
    ("オルカHi ウーブン", "Orca Woven Hi-Tops"),
    ("オレンジアローズ", "Orange Arrows"),
    ("バラズシT セキハン", "Barazushi Sakura Tee"),
    ("FA-01オモテ", "FA-01 Jacket"),
    ("ミックスシャツ グレー", "Gray Mixed Shirt"),
    ("タコマスク", "Gas Mask"),
    ("オレンジボーダーラガー", "Striped Rugby"),
    ("ノリマキ750 ブラック", "Black Norimaki 750s"),
    ("ボルダーシューズ ハザクラ", "Birch Climbing Shoes"),
    ("ウミウシパープル", "Purple Sea Slugs"),
    ("ミルキーダウンブーツ", "Snowy Down Boots"),
    ("エゾッココーチ モエギ", "Zekko Jade Coat"),
    ("チャリキング帽", "Cycle King Cap"),
    ("シンリョクレザーブーツ", "New-Leaf Leather Boots"),
    ("キングベンチNV", "Navy Eminence Jacket"),
    ("エゾッコパーカー アズキ", "Zekko Hoodie"),
    ("サッカーバンド", "Soccer Headband"),
    ("ウミウシタウンHi グレー", "Gray Sea-Slug Hi-Tops"),
    ("イカノメＴ ライトブルー", "Sky-Blue Squideye"),
    ("フィレシャツ サファリ", "Business Animal"),
    ("カモフラパープル", "Purple Camo LS"),
    ("ヤコナイロン ヴィンテージ", "Takoroka Nylon Vintage"),
    ("バイザーメット", "Visor Skate Helmet"),
    ("イカヤキチップ", "Roasted Brogues"),
    ("ヤコタイダイ ギャラクシー", "Takoroka Galactic Tie Dye"),
    ("チャリキングジャージ", "Cycle King Jersey"),
    ("ウラタコスカジャン", "Deep-Octo Satin Jacket"),
    ("フォレストダウン", "Forest Vest"),
    ("アナアキニット アカソデ", "Annaki Red Cuff"),
    ("プルオーバーコート", "Pullover Coat"),
    ("アナアキオンブレネル", "Annaki Flannel Hoodie"),
    ("イロマキ750 レッド", "Red Iromaki 750s"),
    ("エゾッコラグラン", "Zekko Baseball LS"),
    ("わかばイカＴ", "Basic Tee"),
    ("タコボウラーシャツ", "Octobowler Shirt"),
    ("タコサンT", "Tri-Octo Tee"),
    ("グレーチップ イエローソール", "Gray Yellow-Soled Wingtips"),
    ("BSサンダル", "BlobMob Flip-Flops"),
    ("ラバーソール チェリー", "Cherry Kicks"),
    ("スクールジャージー", "School Jersey"),
    ("オイスタークロッグ", "Oyster Clogs"),
    ("クラーゲス528", "Krak-On 528"),
    ("ザ・ベース ボス", "Suede Bosses"),
    ("ダブルエッグサングラス", "Double Egg Shades"),
    ("ウーニーズBBキャップ", "Urchins Cap"),
    ("バラズシT ハクマイ", "Barazushi Rice Tee"),
    ("レタード グリーン", "Green Cardigan"),
    ("サンセットグラデT", "Duskwave Tee"),
    ("アロメテックT レッド", "Red Tentatek Tee"),
    ("マルエリシャツ", "Round-Collar Shirt"),
    ("キングラガー010", "Rugby King 10"),
    ("ソウショクＴ", "Herbivore Tee"),
    ("バニーポップ ブラック", "Black LS"),
    ("デカロニックブラック", "Black Dakroniks"),
    ("タタキBBBシャツ", "Toni K. Baseball Jersey"),
    ("イカスカジャン", "Squid Satin Jacket"),
    ("ホッコリー ネイビー", "Firefin Navy Sweat"),
    ("かくれパイレーツ", "Part-Time Pirate"),
    ("デルタストラップ ネオン", "Neon Delta Straps"),
    ("エゾッコフリッパー", "Zekko Cap"),
    ("デッキシューズ フカイリ", "Dark-Roast Boaties"),
    ("MOVEレッド", "Turbo Tabi Red"),
    ("ギンガムチェック アカ", "Red-Check Shirt"),
    ("キングHKシャツ", "King Jersey"),
    ("バスケジャージ アウェイ", "B-ball Jersey (Away)"),
    ("ハンティングベストKK", "Khaki Ranger Vest"),
    ("スミレビーンズ", "Violet Trainers"),
    ("パラシューター ザクロ", "Crimson Parashooter"),
    ("ガンガゼロックT シロ", "White Urchin Rock Tee"),
    ("デルタストラップ スノー", "Snow Delta Straps"),
    ("キングパーカー グレープ", "Grape Hoodie"),
    ("フィレシャツ アーバン", "Urban Upcycle Top"),
    ("フェイスゴーグル", "Paintball Mask"),
    ("ホタパーカー グレー", "Gray Hoodie"),
    ("マルフグＴ", "Fugu Tee"),
    ("イカブラックV", "Black V-Neck Tee"),
    ("ギンガムチェック ミドリ", "Green-Check Shirt"),
    ("ブロックストライプシャツ", "Striped Shirt"),
    ("マウンテンフローズン", "Chilly Mountain Coat"),
    ("スモークチップ", "Smoky Wingtips"),
    ("ガチホワイト", "White Anchor Tee"),
    ("キャンバスHi トリュフ", "Truffle Canvas Hi-Tops"),
    ("シャンブレーシャツ", "Linen Shirt"),
    ("ホタプラントハット", "Hothouse Hat"),
    ("ウミウシブルー", "Blue Sea Slugs"),
    ("フロントジップベスト", "Front-Zip Vest"),
    ("オルカHi パッション", "Orca Passion Hi-Tops"),
    ("よもぎポロ", "Sage Polo"),
    ("イカイエローVガサネ", "Squid Yellow Layered LS"),
    ("ネイビーチップ レッドソール", "Navy Red-Soled Wingtips"),
    ("チョコクロッグ", "Choco Clogs"),
    ("シアンビーンズ", "Cyan Trainers"),
    ("チリメンタコアロハ", "Chili Octo Aloha"),
    ("サニーオレンジＴ", "Sunny-Day Tee"),
    ("タカアシプロテクターレッド", "Red Battlecrab Shell"),
    ("マウンテンオリーブ", "Olive Ski Jacket"),
    ("ドロップスウェット ポジ", "Positive Longcuff Sweater"),
    ("エゾッココーチ ウコン", "Tumeric Zekko Coat"),
    ("キングラガー008", "Rugby King 08"),
    ("ケンサキコーチ", "Kensa Coat"),
    ("ヤキフグ16bit カーキ", "Khaki 16-Bit FishFry"),
    ("リーグT", "League Tee"),
    ("カモガサネ", "Camo Layered LS"),
    ("エゾッココーチ アカネ", "Zekko Redleaf Coat"),
    ("モトクロスブーツ", "Moto Boots"),
    ("キングタンク ホワイト", "White King Tank"),
    ("イカボウズキャメル", "Kid Clams"),
    ("ボーダーホワイト", "White Striped LS"),
    ("ヤキフグ8bit グレー", "Gray 8-Bit FishFry"),
    ("サキイカホワイト", "Tri-Shred Tee"),
    ("レタード オレンジ", "Orange Cardigan"),
    ("タコピステ ブルー", "Octo Jumper Away"),
    ("フレンドT", "Friend Tee"),
    ("イコT ゴブゴブ", "Octosquid Tandem Tee"),
    ("エゾッコロンTラディッシュ", "Zekko Long Radish Tee"),
    ("トリスカベッチン", "Birded Corduroy Jacket"),
    ("シロシャツ", "White Shirt"),
    ("バスケジャージ ホーム", "B-ball Jersey (Home)"),
    ("シャツノゾキブルー", "Shirt with Blue Hoodie"),
    ("アナアキT ポルポピック", "Annaki Polpo-Pic Tank"),
    ("ピーターパンクタイ ブラッド", "Red Hula Punk with Tie"),
];

/// 日本語名からギアの公式英語名を引く。
pub fn lookup_name_en(name_ja: &str) -> Option<&'static str> {
    GEAR_NAME_EN.iter().find(|(k, _)| *k == name_ja).map(|(_, en)| *en)
}

/// ブランドの日本語名 → 公式英語名（18 ブランド、全種）。
pub const BRAND_NAME_EN: &[(&str, &str)] = &[
    ("バラズシ", "Barazushi"),
    ("ロッケンベルグ", "Rockenberg"),
    ("アタリメイド", "Cuttlegear"),
    ("アナアキ", "Annaki"),
    ("シグレニ", "Inkline"),
    ("ジモン", "Splash Mob"),
    ("アイロニック", "Zink"),
    ("ホタックス", "Skalop"),
    ("ホッコリー", "Firefin"),
    ("アロメ", "Tentatek"),
    ("タタキケンサキ", "Toni Kensa"),
    ("クラーゲス", "Krak-On"),
    ("フォーリマ", "Forge"),
    ("ヤコ", "Takoroka"),
    ("エゾッコ", "Zekko"),
    ("エンペリー", "Enperry"),
    ("バトロイカ", "SquidForce"),
    ("シチリン", "Emberz"),
];

/// ブランドの日本語名から公式英語名を引く。
pub fn lookup_brand_name_en(brand_ja: &str) -> Option<&'static str> {
    BRAND_NAME_EN.iter().find(|(k, _)| *k == brand_ja).map(|(_, en)| *en)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn entries_complete_and_unique() {
        let mut seen = std::collections::HashSet::new();
        for (ja, en) in GEAR_NAME_EN {
            assert!(!ja.is_empty() && !en.is_empty(), "incomplete entry: {ja}");
            assert!(seen.insert(*ja), "duplicate ja name: {ja}");
        }
        assert_eq!(GEAR_NAME_EN.len(), 548);
    }

    #[test]
    fn brand_entries_complete_and_unique() {
        let mut seen = std::collections::HashSet::new();
        for (ja, en) in BRAND_NAME_EN {
            assert!(!ja.is_empty() && !en.is_empty(), "incomplete entry: {ja}");
            assert!(seen.insert(*ja), "duplicate ja name: {ja}");
        }
        assert_eq!(BRAND_NAME_EN.len(), 18);
    }

    #[test]
    fn lookup_known_gear() {
        assert_eq!(lookup_name_en("イトヨリキャップ"), Some("Bream-Brim Cap"));
        assert_eq!(lookup_name_en("unknown"), None);
    }

    #[test]
    fn lookup_known_brand() {
        assert_eq!(lookup_brand_name_en("アロメ"), Some("Tentatek"));
        assert_eq!(lookup_brand_name_en("unknown"), None);
    }
}
