//! ギア（頭防具・服・靴）とブランドの公式英語名（#714 系）。
//!
//! wikiwiki.jp「スプラトゥーン3 攻略＆検証 Wiki」の日英対応表
//! （https://wikiwiki.jp/splatoon3mix/言語別対応表/日英対応表/装備 ・
//! https://wikiwiki.jp/splatoon3mix/ギア/ブランド 、2026-08 時点、
//! ギア833件・ブランド20件）から生成。日本語名の文字列を仲介キーにしている
//! （splabo 側の gear は SplatNet3 の商品名をそのまま key に使っており、
//! splatoon3.ink 等の内部 ID ハッシュと対応しないため）。
//!
//! splatoon3.ink のロケールデータ（548件）は当初の採用候補だったが、
//! サーモンラン報酬の「クマサン商会」ブランド（Grizzco）のギア群を
//! まるごと欠いていたため、より網羅的な wikiwiki.jp のデータに置き換えた
//! （#712 系）。stat.ink の /api/v1/gear は Splatoon 1/2 時代のカタログの
//! 凍結データで論外（255件・S3限定ブランド欠落）。
//!
//! ギアは新シーズンで追加されることがあるため、weapon_static.rs と違い陳腐化しうる。
//! 新ギア追加時は wikiwiki.jp から再取得して追記する。

/// 日本語名 → 公式英語名。
pub const GEAR_NAME_EN: &[(&str, &str)] = &[
    ("イカタコピアス", "Tentaclinger Earring"),
    ("2ラインメッシュ", "Two-Stripe Mesh"),
    ("5パネルキャップ", "Five-Panel Cap"),
    ("イカベーダーキャップ", "Squidvader Cap"),
    ("イシダイストライプスキャップ", "Barrelfish Baseball Hat"),
    ("ウーニーズBBキャップ", "Urchins Cap"),
    ("ウールウーニーズクラシック", "Woolly Urchins Classic"),
    ("エゾッコメッシュ", "Zekko Mesh"),
    ("カモキャップ スイトン", "Seafoam Cap"),
    ("カモキャップ ドトン", "Dustcloud Cap"),
    ("カモメッシュ", "Camo Mesh"),
    ("キャンプキャップ", "Lightweight Cap"),
    ("キングフリップメッシュ", "King Flip Mesh"),
    ("クラゲーダーキャップ", "Jellyvader Cap"),
    ("グンチンハ", "Flounder Flap Cap"),
    ("コーラルキャップ", "Coral Cap"),
    ("シェーディングキャップ スミ", "Ink-Black Flap Cap"),
    ("ジェットキャップ", "Jet Cap"),
    ("スイムキャップ", "Swim Cap"),
    ("チドリキャップ", "Squid-Stitch Cap"),
    ("チャリキング帽", "Cycle King Cap"),
    ("テッカサイクルキャップ", "Cycling Cap"),
    ("ドゥーラグキャップガサネ", "Do-Rag, Cap & Glasses"),
    ("ナイトハイクキャップ", "Headlamp Hat"),
    ("ハウスタグデニムCAP", "House-Tag Denim Cap"),
    ("バックワードキャップ", "Backward Cap"),
    ("ヒッコリーワークキャップ", "Hickory Work Cap"),
    ("ビバレッジキャップ", "Streetstyle Cap"),
    ("フィッシャーマンキャップ", "Wharfside Cap"),
    ("フグハンチング", "Blowfish Newsie"),
    ("フライカーキャップ", "Vintage Biker Cap"),
    ("フライトぼう", "Pilot Hat"),
    ("ブリムリブハット", "Clue-Detecting Cap"),
    ("マリンキャップ", "Cap'n Cap"),
    ("ヤコメッシュ", "Takoroka Mesh"),
    ("ロングビルキャップ", "Long-Billed Cap"),
    ("８ビットフレーム", "Retro Framers"),
    ("アナアキスクエアグラス", "Annaki Charms"),
    ("アナアキバスクベレー", "Annaki Beret & Glasses"),
    ("アローバンド ブラック", "Black Arrowbands"),
    ("アローバンド ホワイト", "White Arrowbands"),
    ("イロメガネ", "Tinted Shades"),
    ("エゾッコフリッパー", "Zekko Cap"),
    ("オクタグラス", "Octoglasses"),
    ("クラムグラス", "Glam Clam Specs"),
    ("クロブチ レトロ", "Retro Specs"),
    ("サンサンサングラス", "Triple-Deck Specs"),
    ("スイミングモーグル", "Swim Goggles"),
    ("スプラッシュゴーグル", "Splash Goggles"),
    ("スミガードゴーグル", "Ink-Guard Goggles"),
    ("セルブロウ", "Half-Rim Glasses"),
    ("ダイバーゴーグル", "Snorkel Mask"),
    ("ダテコンタクト", "Fake Contacts"),
    ("ダブルエッグサングラス", "Double Egg Shades"),
    ("タマサンBC925", "Retro BluFocals"),
    ("タレサン18K", "18K Aviators"),
    ("デメニギスゴーグル", "Ink-Tinted Goggles"),
    ("パーフェクトスリーパー", "Deluxury Sleep Mask"),
    ("バイカーシェード", "Moto Shades"),
    ("パイロットゴーグル", "Pilot Goggles"),
    ("フトブチスクエア", "Hipster Horn-Rims"),
    ("フロート クリアグラス", "Invisifloats"),
    ("マルサンSV925", "SV925 Circle Shades"),
    ("マルベッコー", "Full-Moon Glasses"),
    ("メダイサングラス", "Sea-Me-Nots"),
    ("モーグル タタキベッチュー", "Toni Kensa Goggles"),
    ("ワイヤーグラス", "Glassless Glasses"),
    ("クロヤキフグバンダナ", "Black FishFry Bandana"),
    ("サッカーバンド", "Soccer Headband"),
    ("スカッシュバンド", "Squash Headband"),
    ("テニスバンド", "Tennis Headband"),
    ("バスケバンド", "B-ball Headband"),
    ("ピンポンバンド", "Squidband"),
    ("ヘッドバンド ホワイト", "White Headband"),
    ("ヤキフグビスケットバンダナ", "FishFry Biscuit Bandana"),
    ("ランニングバンド", "Jogging Headband"),
    ("イカバケット", "Bucket Hat"),
    ("イカンカン", "Straw Boater"),
    ("イカンカン クラシック", "Classic Straw Boater"),
    ("ウミユリパイハット", "Sea-Lily Hat"),
    ("エゾッコリーボーラー", "Z+F Flair Bowler"),
    ("カイガラスゲ", "Seashell Bamboo Hat"),
    ("キャンプハット", "Camping Hat"),
    ("サウナハット", "Sauna Hat"),
    ("サファリハット", "Jungle Hat"),
    ("スゲ", "Bamboo Hat"),
    ("ステンシルデニムハット", "Jean Dream Bucket"),
    ("ストローハット", "Beachcomber"),
    ("トレジャーメット", "Treasure Hunter"),
    ("パッチハット", "Patched Hat"),
    ("パラソルチューリップ", "Tulip Parasol"),
    ("フグベルハット", "Blowfish Bell Hat"),
    ("フグベルベルハット", "Fugu Bell Hat"),
    ("フグベルベルベルハット", "Hat-Trick Bell Hat"),
    ("ボーラークラシック", "Classic Bowler"),
    ("ホタテンガロン", "Howdy Hat"),
    ("ホタプラントハット", "Hothouse Hat"),
    ("ムキウニクロシェ", "Urchin Understitch"),
    ("ヤマハット", "Mountie Hat"),
    ("ロブスターブーニー", "Safari Hat"),
    ("イヤーマフ", "Noise Cancelers"),
    ("エンペラフックHDP", "Squidfin Hook Cans"),
    ("オーロラヘッドホン", "Designer Headphones"),
    ("カモヘッドホン スイトン", "Seafoam 'Phones"),
    ("カモヘッドホン ドトン", "Dustcloud 'Phones"),
    ("甲伝導エンペラEP", "Cephalo Pods"),
    ("スタジオヘッドホン", "Studio Headphones"),
    ("ステカセヘッドホン", "Squidlife Headphones"),
    ("ヘッドホン90-d", "Aux Boxes"),
    ("ミミタコ8", "Ocho OctoPhones"),
    ("ミミタコ8 RAW", "Ocho OctoPhones Blancos"),
    ("イカフィットメット", "Slipstream Helmet"),
    ("イカフィットメットPRO", "Slipstream Helmet Pro"),
    ("イカロスHKメット", "Hockey Helmet"),
    ("イシダイSTメット ホーム", "Barrelfish Home Helmet"),
    ("オクトメットプライズデコ", "Octo Tackle Helmet Deco"),
    ("キャッチャーマスクFC", "Away-Team Catcher"),
    ("キャッチャーマスクFU", "Home-Team Catcher"),
    ("サイクルメット", "Bike Helmet"),
    ("シェルメット", "Winkle Stripe Helm"),
    ("スケボーメット", "Skate Helmet"),
    ("チゴフグメット", "ZedFry Helmet"),
    ("ツヤケシMTBメット", "Matte Bike Helmet"),
    ("デカメットアイシールド", "Deca Tackle Visor Helmet"),
    ("ナイトビジョン", "Stealth Goggles"),
    ("バイザーメット", "Visor Skate Helmet"),
    ("ヘッキャ イシダイ", "Barrelfish Headgear"),
    ("ヘッキャ ムジ", "Scrum Cap"),
    ("ホーンメットBF", "Party Hard Hat"),
    ("ロゴヅクシMTBメット", "MTB Helmet"),
    ("アナアキマスク", "Annaki Mask"),
    ("イカスカルマスク", "Skull Bandana"),
    ("イカバッテンガード", "Squid Facemask"),
    ("エイズリーバンダナ", "Paisley Bandana"),
    ("エラブリースマスク", "Air Gills DX"),
    ("キングオブマスク", "King Facemask"),
    ("キングタコスターマスク", "Octoking Facemask"),
    ("タコマスク", "Gas Mask"),
    ("トンビシールドR255", "Squidbeak Shield"),
    ("トンビシールドRGB0", "Stealth Squidbeak Shield"),
    ("ノーズガードモトクロス", "Motocross Nose Guard"),
    ("フェイスゴーグル", "Paintball Mask"),
    ("フォーリマスク", "Forge Mask"),
    ("フォーリマスク デジカモ", "Digi-Camo Forge Mask"),
    ("ブロブスマイルマスク", "BlobMob Mask"),
    ("ペインターマスク", "Painter's Mask"),
    ("マイネームイズマスク", "Meetcha Mask"),
    ("マスクドホッコリー", "Firefin Facemask"),
    ("マルノミウーパー", "Snaxolotl Hood"),
    ("アナアキアンピンベレー", "Annaki Beret"),
    ("アンコウニット", "Anglerfish Knit"),
    ("イカノルディック", "Squid Nordic"),
    ("ウインターボンボン", "Sporty Bobble Hat"),
    ("オシノビニット", "Sneaky Beanie"),
    ("ショートビーニー", "Short Beanie"),
    ("チゴフグニット", "ZedFry Beanie"),
    ("ボーダービーニー", "Striped Beanie"),
    ("ボンボンニット", "Bobble Hat"),
    ("モンゴウベレー", "Special-Forces Beret"),
    ("ヤマギリビーニー", "Yamagiri Beanie"),
    ("リブニット", "Knitted Hat"),
    ("キャディ サンバイザー", "Golf Visor"),
    ("サンサンサンバイザー", "Sun Visor"),
    ("スラグンサンバイザー", "Tee Time Visor"),
    ("フェイスバイザー", "Face Visor"),
    ("ヤキフグ サンバイザー", "FishFry Visor"),
    ("ヤコバイザー", "Takoroka Visor"),
    ("ロブズ・10・バイザー", "Crust Bucket Visor"),
    ("オクトパールクラウン", "Octopearl Crown"),
    ("カイトウ・フック", "Dapperdasher Hat"),
    ("カイノワ", "Coral Wreath"),
    ("カジキマスク", "Bleak Beak"),
    ("キャプテン・カサゴ", "The Plankton Walker"),
    ("キンギョマスケラ", "Golden Gala Masque"),
    ("スケアリーフェイス", "Swim Reaper"),
    ("ヌラネバウィッグ", "Now or Never Horns"),
    ("ヌラネバカチューシャ", "Now or Never Spikes"),
    ("ヌラネバカベッサ", "Now or Never Headdress"),
    ("ヌラネバキャップ", "Now or Never Cap"),
    ("ヌラネバクラウン", "Now or Never Crown"),
    ("ヌラネババレッタ", "Now or Never Barrette"),
    ("ヌラネバピアス", "Now or Never Earrings"),
    ("ノベルティグラス アネモネ", "Pink Pinhole Shades"),
    ("ノベルティグラス タンポポ", "Yellow Pinhole Shades"),
    ("ノベルティグラス ムスカリ", "Teal Pinhole Shades"),
    ("ノベルティグラス ヨツバ", "Green Pinhole Shades"),
    ("フェスフェイス カサゴ", "Lionfish Funface"),
    ("フェスフェイス キツネ", "Fox Funface"),
    ("フェスフェイス サルカニ", "Monkey-Crab Funface"),
    ("フェスフェイス スマイル", "Cartoony Funface"),
    ("フェスフェイス チゴフグ", "ZedFry Funface"),
    ("フェスフェイス ハコフグ", "Cowfish Funface"),
    ("マミイカヘッド", "Undead Head"),
    ("クマノミミ", "Teddy Band"),
    ("ヒーローブレイン レプリカ", "Hero Mindset Replica"),
    ("イカイノカメン", "Parallel Mask"),
    ("オーダーピアス レプリカ", "Order Earring Replica"),
    ("オーダーレギュ レプリカ", "Order Regulator Replica"),
    ("ヒメグルミ", "Pearl Plushie"),
    ("ブレインウォッシュVE", "Controller VM"),
    ("アーマーメット レプリカ", "Armor Helmet Replica"),
    ("イイダチヘッドホン", "Marinated Headphones"),
    ("イカカゲマスク甲", "Squinja Mask Mk I"),
    ("イカカゲマスク乙", "Squinja Mask Mk II"),
    ("イカクリップ", "Squid Clip-Ons"),
    ("イカパッチン", "Squid Hairclip"),
    ("エンチャントハット", "Enchanted Hat"),
    ("オシャブリボーン", "Boss Floss"),
    ("オナガノオモテ", "Onaga Mask"),
    ("サムライヘルメット", "Samurai Helmet"),
    ("タコティカルなヘルム", "Steel Helm"),
    ("タコハチ", "Sushi Sous-Chef Band"),
    ("バーサークヘル", "Chaos Helm"),
    ("パワードマスク", "Power Mask"),
    ("パワードマスク オリジン", "Power Mask Mk I"),
    ("ヒーローヘッズ レプリカ", "Hero Headset Replica"),
    ("ヒメイトクラウンL", "Pearlescent Crown L"),
    ("ヒメイトクラウンS", "Pearlescent Crown S"),
    ("ひれおくん", "Fresh Fish Head"),
    ("ホホジロノオモテ", "Hohojiro Mask"),
    ("マンダノオモテ", "Manta Mask"),
    ("アイアンマスカレイド", "Welding Mask"),
    ("アセストップソシナ", "Worker's Head Towel"),
    ("イトヨリキャップ", "Bream-Brim Cap"),
    ("ウキアガールRB", "3D Glasses"),
    ("エル・カラマレス", "El Rey Calamar"),
    ("ガーディアンアーミーハット", "Beekeeper Hat"),
    ("ガーディアンズキャップ", "Commander Cap"),
    ("シカイバイザー", "Lo-Vis Visor"),
    ("ショーグンメット", "Octavio Dome"),
    ("スペボウ レプリカ", "Worker's Cap"),
    ("ゾネスティックスコープ", "Octoleet Goggles"),
    ("タコツボメット", "Deep Sinker Helm"),
    ("ダストブロッカー 2.5", "Dust Blocker 2000"),
    ("ハイテクスコープ", "360 All-Scopes"),
    ("バイトヘルメット レプリカ", "Hard Hat Replica"),
    ("ハイパーミライヘッド", "Retro Future Helmet"),
    ("パイロットメット", "Astro Helm"),
    ("ヒラメキブレインメット", "Brain Strainer"),
    ("ヘッドライトヘルム", "Headlamp Helmet"),
    ("マリリンハットウィズピンズ", "Sailor Cap"),
    ("マルミエールUD", "See-an-Enemy HUD"),
    ("レジェンドのぼうし", "Cap of Legend"),
    ("ジャッジメントイヤー", "Judicial Hearing"),
    ("ロブキャップ", "Stay Crusty Cap"),
    ("ω-3T", "ω-3 Tee"),
    ("アイスグラデT", "Icewave Tee"),
    ("アナアキT アシメブレス", "Annaki Bracelet Tee"),
    ("アナアキT チョーカー", "Annaki Choker Tee"),
    ("アナアキT ポルポピック", "Annaki Polpo-Pic Tank"),
    ("アロメT ゴブゴブ", "Tentatek Tandem"),
    ("アロメスローガンT", "Tentatek Slogan Tee"),
    ("イカサンT", "Tri-Squid Tee"),
    ("イカジャマイカ", "Reggae Tee"),
    ("イカノメＴ ブラック", "Black Squideye"),
    ("イカノメＴ ライトブルー", "Sky-Blue Squideye"),
    ("イカブラック", "Black Tee"),
    ("イカブラックV", "Black V-Neck Tee"),
    ("イカホワイト", "White Tee"),
    ("イカホワイトV", "White V-Neck Tee"),
    ("イコT ゴブゴブ", "Octosquid Tandem Tee"),
    ("エゾッコリーT ネイビー", "Navy Z+F Tee"),
    ("エゾッコリーT ホワイト", "White Z+F Tee"),
    ("ガチブラック", "Black Anchor Tee"),
    ("ガチホワイト", "White Anchor Tee"),
    ("ガブリエルT", "Eelzebub Tee"),
    ("ガンガゼロックT クロ", "Black Urchin Rock Tee"),
    ("ガンガゼロックT シロ", "White Urchin Rock Tee"),
    ("キングHKシャツ", "King Jersey"),
    ("キングオクトHKシャツ", "Octoking HK Jersey"),
    ("キングオクトTブラックベロア", "Black Velour Octoking Tee"),
    ("キングオクトTミドリベロア", "Green Velour Octoking Tee"),
    ("キングシースルーT", "King Mesh Tee"),
    ("グレープＴ", "Grape Tee"),
    ("コントレイルボーダー", "Zontal Ztripe Tee"),
    ("サキイカホワイト", "Tri-Shred Tee"),
    ("サニーオレンジＴ", "Sunny-Day Tee"),
    ("サンセットグラデT", "Duskwave Tee"),
    ("スウェットT ゴブ", "Half-Sleeve Sweater"),
    ("スシズメブロブ ベリー", "Berry BlobMob Tee"),
    ("スシズメブロブ ライム", "Lime BlobMob Tee"),
    ("ソウショクＴ", "Herbivore Tee"),
    ("タコＴ", "Octo Tee"),
    ("タコサンT", "Tri-Octo Tee"),
    ("チドリメロンＴ", "Squid-Stitch Tee"),
    ("デカロTキウイ", "Dakro Nana Tee"),
    ("デカロTゴールデン", "Dakro Golden Tee"),
    ("デカロゴＴ シロ", "White Deca Logo Tee"),
    ("デカロゴT ノーコン", "Navy Deca Logo Tee"),
    ("トワイライトグラデT", "Vaporwave Tee"),
    ("ニクショクＴ", "Carnivore Tee"),
    ("パールドットＴ", "Pearl Tee"),
    ("パイレーツボーダー", "Pirate-Stripe Tee"),
    ("バラズシ アカシソマキ", "Plum Barazushi Wrap"),
    ("バラズシ ノリマキ", "Barazushi Wrap"),
    ("バラズシT ゲンマイ", "Barazushi Black Tee"),
    ("バラズシT セキハン", "Barazushi Sakura Tee"),
    ("バラズシT ハクマイ", "Barazushi Rice Tee"),
    ("バンドT ABXY", "Chirpy Chips Band Tee"),
    ("バンドT HIGHTIDEERA", "Hightide Era Band Tee"),
    ("バンドT SQUIDSQUAD", "Squid Squad Band Tee"),
    ("バンドT WETFLOOR", "Wet Floor Band Tee"),
    ("ビバレッジT セサミン", "Slate Streetstyle Tee"),
    ("ビバレッジT リコピン", "Lyco-P Streetstyle Tee"),
    ("フェスＴ", "Splatfest Tee"),
    ("フレンドT", "Friend Tee"),
    ("ベクトルパターン グレー", "Gray Vector Tee"),
    ("ベクトルパターン レッド", "Red Vector Tee"),
    ("ホットグラデT", "Firewave Tee"),
    ("マリンボーダー", "Sailor-Stripe Tee"),
    ("マルフグＴ", "Fugu Tee"),
    ("ミズシュラッグT", "Missus Shrug Tee"),
    ("ミスターシュラッグT", "Mister Shrug Tee"),
    ("ミントＴ", "Mint Tee"),
    ("ヤキフグ8bit グレー", "Gray 8-Bit FishFry"),
    ("ヤキフグ8bit ブラック", "Black 8-Bit FishFry"),
    ("ヤキフグ8bit ホワイト", "White 8-Bit FishFry"),
    ("ヤコT ゴブゴブ", "Takoroka Tandem"),
    ("ヤコT ヘヴィクラブ", "Takoroka \\\\m/ Crab"),
    ("ヤコT メタルエイリアン", "Takoroka \\\\m/ Alien"),
    ("ヤコタイダイ ギャラクシー", "Takoroka Galactic Tie Dye"),
    ("ヤコタイダイ レインボー", "Takoroka Rainbow Tie Dye"),
    ("ヤマビコＴ アイボリー", "Ivory Peaks Tee"),
    ("ヤマビコＴ ブルー", "Blue Peaks Tee"),
    ("リーグT", "League Tee"),
    ("リイシューT ブラウン", "Tan Retro Tee"),
    ("リイシューT ブルー", "Blue Retro Tee"),
    ("リイシューT ホワイト", "White Retro Tee"),
    ("リンガーT アップル", "Apple Ringer"),
    ("リンガーT パイン", "Pineapple Ringer"),
    ("レイニーブルーＴ", "Rainy-Day Tee"),
    ("ロッケンベルグＴ ブラック", "Rockenberg Black"),
    ("ロッケンベルグＴ ホワイト", "Rockenberg White"),
    ("わかばイカＴ", "Basic Tee"),
    ("わかばタコT", "Fresh Octo Tee"),
    ("F-010", "Forge Octarian Jacket"),
    ("F-190", "Forge Inkling Parka"),
    ("F-3 ペイントカスタム", "Custom Painted F-3"),
    ("F-3 ホワイトレザー", "White Leather F-3"),
    ("FA-01ウラ", "FA-01 Reversed"),
    ("FA-01オモテ", "FA-01 Jacket"),
    ("FCジャージー", "Retro Gamer Jersey"),
    ("アナアキダッフル", "Annaki Tuff Duffel"),
    ("アナアキダブルジャケット", "Annaki Anchored Coat"),
    ("イカスカジャン", "Squid Satin Jacket"),
    ("イカセーラー ブルー", "Blue Sailor Suit"),
    ("イカセーラー ホワイト", "White Sailor Suit"),
    ("イカライダーBLACK", "Black Inky Rider"),
    ("イカライダーWHITE", "White Inky Rider"),
    ("イチニンバオリ", "Indigo Boss Haori"),
    ("ウラスカジャン", "Zapfish Satin Jacket"),
    ("ウラタコスカジャン", "Deep-Octo Satin Jacket"),
    ("エゾッココーチ アカネ", "Zekko Redleaf Coat"),
    ("エゾッココーチ ウコン", "Tumeric Zekko Coat"),
    ("エゾッココーチ モエギ", "Zekko Jade Coat"),
    ("オールウェイズファン", "Airflow & Hustle Jacket"),
    ("オスモル アース", "Rugby Fleece"),
    ("オスモル アイボリー", "Cream Tundra Fleece"),
    ("キングベンチNV", "Navy Eminence Jacket"),
    ("クラーゲス528", "Krak-On 528"),
    ("クンフージャージ", "Kung-Fu Zip-Up"),
    ("クンフーパンジャージ", "Panda Kung-Fu Zip-Up"),
    ("ケンサキコーチ", "Kensa Coat"),
    ("コテボレロ ネガ", "Orca Bolero"),
    ("コテボレロ ポジ", "Penguin Bolero"),
    ("スクールジャージー", "School Jersey"),
    ("スタジャンフカマシ", "Chompers Varsity Jacket"),
    ("スタジャンロゴマシ", "Varsity Jacket"),
    ("チェックテーラード", "Tenured Turtleneck"),
    ("トリスカベッチン", "Birded Corduroy Jacket"),
    ("ハウスタグホエールニット", "Whale-Knit Sweater"),
    ("パドリングジャケット ネガ", "Ink-Black Paddle Jack"),
    ("パドリングジャケット ポジ", "Light-Bright Paddle Jack"),
    ("バラズシダッフル", "Barazushi Tuff Duffel"),
    ("バラズシピーコート", "Barazushi Peacoat"),
    ("バラズシヤッケ", "Barazushi Anorak"),
    ("バラズシライナー", "Barazushi Liner Shell"),
    ("ハンティングジャケットKK", "Dusty Field Jacket"),
    ("フィレジャケット", "Patchwork Bomber"),
    ("プルオーバーコート", "Pullover Coat"),
    ("ボンバージャケット ネガ", "Dark Bomber Jacket"),
    ("ボンバージャケット ポジ", "Light Bomber Jacket"),
    ("マウンテン アオサ", "Lime Ski Jacket"),
    ("マウンテンオリーブ", "Olive Ski Jacket"),
    ("マウンテンチリペッパー", "Chili-Pepper Ski Jacket"),
    ("マウンテンノリタマゴ", "Lemon Mountain Coat"),
    ("マウンテンフローズン", "Chilly Mountain Coat"),
    ("マウンテンベリー", "Berry Ski Jacket"),
    ("マッチャ ライトダウン", "Matcha Down Jacket"),
    ("モンスター PCU56", "Arctic Monster Parka"),
    ("ヤコナイロン ヴィンテージ", "Takoroka Nylon Vintage"),
    ("ヤコナイロン ノスタルジア", "Takoroka Nineties Nylon"),
    ("ヤコナイロンレトロ", "Takoroka Windcrusher"),
    ("レタード オレンジ", "Orange Cardigan"),
    ("レタード グリーン", "Green Cardigan"),
    ("ロッケンブレイクジャケット", "Rockin' Leather Jacket"),
    ("FCカラスミ", "Slipstream United"),
    ("アオサドーレ", "FC Albacore"),
    ("オレンジボーダーラガー", "Striped Rugby"),
    ("キングラガー008", "Rugby King 08"),
    ("キングラガー010", "Rugby King 10"),
    ("さくらエビポロ", "Shrimp-Pink Polo"),
    ("チャリキングジャージ", "Cycle King Jersey"),
    ("テッカサイクルシャツ", "Cycling Shirt"),
    ("トリコロールラガー", "Tricolor Rugby"),
    ("ピンポンポロ", "Black Polo"),
    ("よもぎポロ", "Sage Polo"),
    ("エゾッコパーカー アズキ", "Zekko Hoodie"),
    ("エゾッコパーカー ウグイス", "Olive Zekko Parka"),
    ("カモパーカー スイトン", "Seafoam Hoodie"),
    ("カモパーカー ドトン", "Dustcloud Hoodie"),
    ("キングパーカー グレープ", "Grape Hoodie"),
    ("ジップアップ カモ", "Camo Zip Hoodie"),
    ("ジップアップ グリーン", "Green Zip Hoodie"),
    ("シャツノゾキピンク", "Pink Hoodie"),
    ("シャツノゾキブルー", "Shirt with Blue Hoodie"),
    ("バハフーディー セレステ", "Sudadera Celeste"),
    ("バハフーディー ロホ", "Sudadera Roja"),
    ("ホタパーカー グレー", "Gray Hoodie"),
    ("ホタパーカー ブラック", "Black Hoodie"),
    ("ホタプラントパーカー", "Hothouse Hoodie"),
    ("アナアキオンブレネル", "Annaki Flannel Hoodie"),
    ("イカスタンシャツ", "Rodeo Shirt"),
    ("イシダイストライプスユニ", "Barrelfish Baseball Uni"),
    ("ヴィンテージチェック", "Vintage Check Shirt"),
    ("ウーニーズBBシャツ", "Urchins Jersey"),
    ("オーシャンリゾートアロハ", "Coral Bloom Aloha"),
    ("オータムネル", "Lumberjack Shirt"),
    ("おどるイカアロハ", "Aloha Shirt"),
    ("ギンガムチェック アカ", "Red-Check Shirt"),
    ("ギンガムチェック ミドリ", "Green-Check Shirt"),
    ("ジャコスカウト", "Trooper Top"),
    ("ジャコスカウト ハマチ", "Kelp Trooper Top"),
    ("シャンブレーシャツ", "Linen Shirt"),
    ("シロシャツ", "White Shirt"),
    ("ステッチシャツ ヤガラ", "Fancyfish Stitch"),
    ("スミカケシャツ", "Inkfall Shirt"),
    ("スミコボシシャツ", "Dark Splash Shirt"),
    ("スミチラシシャツ", "Fashion Splash Shirt"),
    ("スミヌキシャツ", "Ink-Wash Shirt"),
    ("タイシャツ", "Shirt & Tie"),
    ("タイツキベイビークラゲ", "Baby-Jelly Shirt & Tie"),
    ("タコボウラーシャツ", "Octobowler Shirt"),
    ("タタキBBBシャツ", "Toni K. Baseball Jersey"),
    ("タツノコキューバ", "Seahorse Shoreliner"),
    ("チリメンタコアロハ", "Chili Octo Aloha"),
    ("パッチワークシャツ", "Rad Plaid Casual"),
    ("パラシューター ザクロ", "Crimson Parashooter"),
    ("パラシューター プルーン", "Prune Parashooter"),
    ("バンドカラー ストライプ", "Hype Stripe Button Up"),
    ("バンドカラー ムジ", "Base White Button Up"),
    ("ピーターパンクシャツ", "Hula Punk Shirt"),
    ("ピーターパンクタイ ブラッド", "Red Hula Punk with Tie"),
    ("ピエロシャツ", "Button-Clown Shirt"),
    ("フィレシャツ アーバン", "Urban Upcycle Top"),
    ("フィレシャツ サファリ", "Business Animal"),
    ("ブロックストライプシャツ", "Striped Shirt"),
    ("ベイビークラゲシャツ", "Baby-Jelly Shirt"),
    ("マルエリシャツ", "Round-Collar Shirt"),
    ("ミスターベースボール", "Baseball Jersey"),
    ("ミックスシャツ グレー", "Gray Mixed Shirt"),
    ("レイヤードットシャツ", "Dots-on-Dots Shirt"),
    ("ロゴマシマシアロハ", "Logo Aloha Shirt"),
    ("3Dニット シャーク", "Apex Sweater"),
    ("3Dニット ホエール", "Moby Knit"),
    ("CFHパーカー", "Fringehead Hoodless"),
    ("アナアキニット アオソデ", "Annaki Blue Cuff"),
    ("アナアキニット アカソデ", "Annaki Red Cuff"),
    ("アナアキニット キソデ", "Annaki Yellow Cuff"),
    ("イカバッテン マスタード", "Squidmark Sweat"),
    ("イカリスウェット", "Anchor Sweat"),
    ("エンペーサートレーナー", "N-Pacer Sweat"),
    ("オクタリアンレトロ", "Octarian Retro"),
    ("カレッジスウェット グレー", "Gray College Sweat"),
    ("カレッジスウェット ネイビー", "Navy College Sweat"),
    ("クラマナスウェット", "Manatee Swag Sweat"),
    ("ショートニットカサネ", "Short Knit Layers"),
    ("タコピステ ブルー", "Octo Jumper Away"),
    ("タコピステ ホワイト", "Octo Jumper Home"),
    ("ドロップスウェット ネガ", "Negative Longcuff Sweater"),
    ("ドロップスウェット ポジ", "Positive Longcuff Sweater"),
    ("フードレスパーカー イエロー", "Lemon Hoodless"),
    ("フードレスパーカー グリーン", "Lime Hoodless"),
    ("フードレスパーカー マルチ", "Motley Hoodless"),
    ("ホッコリー ネイビー", "Firefin Navy Sweat"),
    ("ヤコピステ", "Takoroka Jersey"),
    ("リールロールスウェット", "Reel Sweat"),
    ("レトロジャッジ", "Retro Sweat"),
    ("ワケワカメニット", "Fuzzly Sweater"),
    ("アイロニックロング", "Zink LS"),
    ("アナアキロンT イボルブ", "Annaki Evolution Tee"),
    ("アナアキロンT ドライブ", "Annaki Drive Tee"),
    ("イカバッテンロング", "Squidmark LS"),
    ("エゾッコラグラン", "Zekko Baseball LS"),
    ("エゾッコロンTキャロット", "Zekko Long Carrot Tee"),
    ("エゾッコロンTラディッシュ", "Zekko Long Radish Tee"),
    ("カモフラパープル", "Purple Camo LS"),
    ("カラマリフック ディープ", "Deepsea Tangle Top"),
    ("カラマリフック ブラック", "Ink-Black Tangle Top"),
    ("カレッジラグラン", "Varsity Baseball LS"),
    ("シャークラグラン", "Sharkfin Raglan"),
    ("タコロンT 赤", "Red Cuttlegear LS"),
    ("タコロンT 黒", "Black Cuttlegear LS"),
    ("トビウォーズHKユニ", "Inkopolis Squaps Jersey"),
    ("バトロング ホワイト", "White LS"),
    ("バニーポップ ブラック", "Black LS"),
    ("ハラグロラグラン", "Black Baseball LS"),
    ("ハラシロラグラン", "White Baseball LS"),
    ("ボーダーネイビー", "Navy Striped LS"),
    ("ボーダーホワイト", "White Striped LS"),
    ("ボーダーモスグリーン", "Green Striped LS"),
    ("ヤキフグ16bit カーキ", "Khaki 16-Bit FishFry"),
    ("ヤキフグ16bit ブルー", "Blue 16-Bit FishFry"),
    ("ヤコラグランクレイジー", "Takoroka Crazy Baseball LS"),
    ("ヤマビコボーダー", "Striped Peaks LS"),
    ("ゆとりボーダー ピンク", "Pink Easy-Stripe Shirt"),
    ("ゆとりボーダー ライム", "Lime Easy-Stripe Shirt"),
    ("アイロニックレイヤード", "Zink Layered LS"),
    ("アロメテックT ブルー", "Blue Tentatek Tee"),
    ("アロメテックT レッド", "Red Tentatek Tee"),
    ("イカイエローVガサネ", "Squid Yellow Layered LS"),
    ("かくれパイレーツ", "Part-Time Pirate"),
    ("ガチガサネ", "Layered Anchor LS"),
    ("カモガサネ", "Camo Layered LS"),
    ("グリーンＴ", "Green Tee"),
    ("チョコガサネ", "Choco Layered LS"),
    ("ベクトルラインガサネ", "Layered Vector LS"),
    ("マスタードガサネ", "Yellow Layered LS"),
    ("レイヤード ブラック", "Black Layered LS"),
    ("レイヤード ホワイト", "White Layered LS"),
    ("ウミボーズ アウェイ", "Umibozu Road Jersey"),
    ("ウミボーズ ホーム", "Umibozu Home Jersey"),
    ("キングタンク スラッシュ", "Slash King Tank"),
    ("キングタンク ホワイト", "White King Tank"),
    ("キングタンク マリン", "Navy King Tank"),
    ("バスケジャージ アウェイ", "B-ball Jersey (Away)"),
    ("バスケジャージ ホーム", "B-ball Jersey (Home)"),
    ("ロブスターズユニ", "Lob-Stars Jersey"),
    ("アーバンベスト イエロー", "Yellow Urban Vest"),
    ("アーバンベスト ナイト", "Dark Urban Vest"),
    ("アロメサイクルベスト", "Tentatek Slipstream Vest"),
    ("アロメランベスト シルバー", "Silver Tentatek Vest"),
    ("イカゴッチンベスト", "Squid-Pattern Waistcoat"),
    ("イカノボリベスト", "Squidstar Waistcoat"),
    ("ゴマサバスポーティージレ", "Teal Body Warmer"),
    ("スミコボシベスト", "Dark Distressed Vest"),
    ("スミチラシベスト", "Distressed Vest"),
    ("タカアシプロテクターライム", "Lime Battlecrab Shell"),
    ("タカアシプロテクターレッド", "Red Battlecrab Shell"),
    ("ハンティングベストBK", "Black Ranger Vest"),
    ("ハンティングベストKK", "Khaki Ranger Vest"),
    ("フィッシャーズベスト オジ", "Fishing Vest"),
    ("フォレストダウン", "Forest Vest"),
    ("フロントジップベスト", "Front-Zip Vest"),
    ("マウンテンダウン", "Mountain Vest"),
    ("ヒーロースーツ レプリカ", "Hero Suit Replica"),
    ("オーダースーツ レプリカ", "Order Suit Replica"),
    ("アーマージャケット レプリカ", "Armor Jacket Replica"),
    ("イイダチトップス", "Marinated Top"),
    ("エンチャントローブL", "Enchanted Robe B"),
    ("エンチャントローブS", "Enchanted Robe A"),
    ("オナガノハゴロモ", "Eelneck Tank"),
    ("サキイカガクラン", "Schoolyard Scrap Jack"),
    ("サムライジャケット", "Samurai Jacket"),
    ("ジュウドウギ クロオビ", "Black-Belt Gi"),
    ("スクールカーデ ネクタイ", "School Cardigan B"),
    ("スクールカーデ リボン", "School Cardigan A"),
    ("スクールブレザーL", "School Uniform A"),
    ("スクールブレザーR", "School Uniform B"),
    ("タコティカルなよろい", "Steel Platemail"),
    ("ニンジャスーツ", "Squinja Suit"),
    ("バーサークアーマー", "Chaos Commander Suit"),
    ("パワードスーツ", "Power Armor"),
    ("パワードスーツ オリジン", "Power Armor Mk I"),
    ("ヒーロージャケット レプリカ", "Hero Jacket Replica"),
    ("ヒメイトパーカー", "Pearlescent Hoodie"),
    ("ひれおくんのて", "Fresh Fish Gloves"),
    ("ホホジロノハゴロモ", "Chomp Top"),
    ("マンダノカッパ", "Big Slick"),
    ("アカシックコート", "SRL Coat"),
    ("アゲアゲ・10・プラーXXL", "Crustwear XXL"),
    ("アンカーベスト", "Anchor Life Vest"),
    ("イカテンくんポロ", "Squiddor Polo"),
    ("エネルギッシュジャケット", "Cooler Jacket"),
    ("ガーディアンズスーツ", "Commander Tunic"),
    ("カリスマシンガージャケット", "Brinestone Jacket"),
    ("ジムパーソンアーマー", "Office Attire"),
    ("ゾネスティックプロテクター", "Octoleet Armor"),
    ("デベロッパーズワークウエア", "Dev Uniform"),
    ("ナリキリハイテクスーツ", "Astro Wear"),
    ("ハイパーミライスーツ", "Retro Future Suit"),
    ("ハリキリインベンター", "Hacker Jacket"),
    ("フューエルブルゾン", "Juice Parka"),
    ("フロムキタグニ87", "North-Country Parka"),
    ("マクレGT", "Garden Gear"),
    ("ミライスタージャケット", "SplatJack 5000"),
    ("アゲアゲコロモ", "Crispy Crustume"),
    ("ジャッジメントハンド", "Frivolous Paw Suit"),
    ("アイスダウンブーツ", "Icy Down Boots"),
    ("アナアキスパイダー6ホール", "Annaki Arachno Boots"),
    ("ウォームブーツ", "Fuzzy Boots"),
    ("エンジニアブーツ", "Buckle-Down Boots"),
    ("カセブカブーツ ダップル", "Dappled Hammertreads"),
    ("カセブカブーツ レッド", "Red Hammertreads"),
    ("カモチャームブーツ", "Transom Note Boots"),
    ("シンカイレザーブーツ", "Deepsea Leather Boots"),
    ("シンリョクレザーブーツ", "New-Leaf Leather Boots"),
    ("ダックブーツ カクタス", "Spiked Duck Boots"),
    ("ダックブーツ スノウ", "Arctic Duck Boots"),
    ("ダックブーツ ブッシュ", "Field Duck Boots"),
    ("チャバハンティングブーツ", "Tea-Green Hunting Boots"),
    ("ヌバックブーツ イエロー", "Tan Work Boots"),
    ("ヌバックブーツ レッド", "Red Work Boots"),
    ("ヌバックブーツxSJ", "Skipjack Work Boots"),
    ("ハンティングブーツ", "Hunting Boots"),
    ("ミルキーダウンブーツ", "Snowy Down Boots"),
    ("モトクロス ソリッドブルー", "Blue Moto Boots"),
    ("モトクロスM-DCB", "Blu-Shift Moto Boots"),
    ("モトクロスM-DCR", "Red-Shift Moto Boots"),
    ("モトクロスブーツ", "Moto Boots"),
    ("レイニーアセロラ", "Acerola Rain Boots"),
    ("レイニーシャボン", "Bubble Rain Boots"),
    ("レイニーモスグリーン", "Green Rain Boots"),
    ("ロッキンイエロー", "Punk Yellows"),
    ("ロッキンチェリー", "Punk Cherries"),
    ("ロッキンピンク", "Punk Pinks"),
    ("ロッキンブラック", "Punk Nights"),
    ("ロッキンホワイト", "Punk Whites"),
    ("アケビコンフォート", "Plum Casuals"),
    ("ブルーベリーコンフォート", "Blueberry Casuals"),
    ("アナアキラバー ハバネロ", "Annaki Habaneros"),
    ("アナアキラバー フェイク", "Annaki Tigers"),
    ("イカスミチップ", "Squink Wingtips"),
    ("イカボウズキャメル", "Kid Clams"),
    ("イカボウズジェットブラック", "Inky Kid Clams"),
    ("イカヤキチップ", "Roasted Brogues"),
    ("グレーチップ イエローソール", "Gray Yellow-Soled Wingtips"),
    ("シーホースビットローファー", "Bit 'n' Bridle Loafers"),
    ("スモークチップ", "Smoky Wingtips"),
    ("チャッカブーツ サンド", "Desert Chukkas"),
    ("デッキシューズ フカイリ", "Dark-Roast Boaties"),
    ("デッキシューズ ブレンド", "Tricolor Boaties"),
    ("ネイビーチップ レッドソール", "Navy Red-Soled Wingtips"),
    ("ラバーソール ターコイズ", "Turquoise Kicks"),
    ("ラバーソール チェリー", "Cherry Kicks"),
    ("ラバーソール ホワイト", "White Kicks"),
    ("BBサンダル", "Black Flip-Flops"),
    ("BSサンダル", "BlobMob Flip-Flops"),
    ("アナアキストラップ レザー", "Annaki Strappy Sandals"),
    ("アローズサンダル アオキ", "Arrow Toesies Blu"),
    ("アローズサンダル ムラキ", "Arrow Toesies Purp"),
    ("イカニラミサボ", "Skirmish Sabots"),
    ("イカボーンサンダル", "Squid Bone Unslips"),
    ("エゾックロッグ イエロー", "Yellow Toejamz"),
    ("エゾックロッグ グリーン", "Green Toejamz"),
    ("エゾックロッグ ネイビー", "Navy Toejamz"),
    ("エゾックロッグ レッド", "Red Toejamz"),
    ("オイスタークロッグ", "Oyster Clogs"),
    ("チョコクロッグ", "Choco Clogs"),
    ("デルタストラップ スノー", "Snow Delta Straps"),
    ("デルタストラップ ネオン", "Neon Delta Straps"),
    ("デルタストラップ ルミナス", "Luminous Delta Straps"),
    ("フィッシュボーンワラチ", "Cuttlefish Sandies"),
    ("フジツボペタサン", "Musselforge Flip-Flops"),
    ("べリべリサン オレンジ", "Orange Dadfoot Sandals"),
    ("べリべリサン シアン", "Cyan Dadfoot Sandals"),
    ("べリべリサン マゼンタ", "Pink Dadfoot Sandals"),
    ("ホネナラベサボ", "Fishbone Sabots"),
    ("ヤキフグシャワサン アカ", "Red FishFry Sandals"),
    ("ヤキフグシャワサン キ", "Yellow FishFry Sandals"),
    ("01STER カンロ", "Onyx 01STERs"),
    ("01STER コハク", "Pearl 01STERs"),
    ("イロマキ750 イエロー", "Yellow Iromaki 750s"),
    ("イロマキ750 オレンジ", "Orange Iromaki 750s"),
    ("イロマキ750 グリーン", "Green Iromaki 750s"),
    ("イロマキ750 パープル", "Purple Iromaki 750s"),
    ("イロマキ750 ブルー", "Blue Iromaki 750s"),
    ("イロマキ750 レッド", "Red Iromaki 750s"),
    ("ウノアシHi", "Zebrafish Hi-Tops"),
    ("ウミウシタウンHi アンバー", "Amber Sea Slug Hi-Tops"),
    ("ウミウシタウンHi グレー", "Gray Sea-Slug Hi-Tops"),
    ("エギング3 ZY", "Crab-Trap Squidkid III"),
    ("エギング3 アオクロシロ", "Blue & Black Squidkid III"),
    ("エギング3 アカシロクロ", "Red & White Squidkid III"),
    ("エギング4 アオクロ", "Blue & Black Squidkid IV"),
    ("エギング4 アカクロ", "Red & Black Squidkid IV"),
    ("エギング4 キイコン", "Sun & Shade Squidkid IV"),
    ("エギング5 クロアオ", "Black & Blue Squidkid V"),
    ("エギング5 シロアカ", "Red & White Squidkid V"),
    ("エギング5 ハニオレ", "Honey & Orange Squidkid V"),
    ("エンペリアルNV", "Navy Enperrials"),
    ("オルカHi", "Orca Hi-Tops"),
    ("オルカHi ウーブン", "Orca Woven Hi-Tops"),
    ("オルカHi サンセット", "Sunset Orca Hi-Tops"),
    ("オルカHi パッション", "Orca Passion Hi-Tops"),
    ("カモスニーカー スイトン", "Seafoam Hi-Tops"),
    ("カモスニーカー ドトン", "Dustcloud Hi-Tops"),
    ("キャンバスHi トマト", "Red Hi-Tops"),
    ("キャンバスHi トリュフ", "Truffle Canvas Hi-Tops"),
    ("キャンバスHi マッシュルーム", "Cream Hi-Tops"),
    ("キャンバスHi モロヘイヤ", "Hunter Hi-Tops"),
    ("ゴマシオ270", "Sesame Salt 270s"),
    ("シーホースHi ゴールド", "Gold Hi-Horses"),
    ("シーホースHi ゾンビ", "Zombie Hi-Horses"),
    ("シーホースHi パープル", "Purple Hi-Horses"),
    ("シーホースHi レッド", "Red Hi-Horses"),
    ("シャークモカシン", "Shark Moccasins"),
    ("ジョーズモカシン", "Mawcasins"),
    ("ストリップ タタキベッチュー", "Toni Kensa Black Hi-Tops"),
    ("デカロニックチョコレート", "Chocolate Dakroniks"),
    ("デカロニックブラック", "Black Dakroniks"),
    ("デカロニックミント", "Cyan Dakroniks"),
    ("テンヤ8 パープル", "Tenya OctoPurps"),
    ("テンヤ8 レッド", "Tenya OctoReds"),
    ("ノリマキ750 ブラック", "Black Norimaki 750s"),
    ("ノリマキ750 ホワイト", "White Norimaki 750s"),
    ("パーチHi ホワイト", "White Lo-Vert Hi-Tops"),
    ("パワーストリップ アオアシ", "Blue Power Stripes"),
    ("パワーストリップ アカアシ", "Red Power Stripes"),
    ("パワーリセットHi", "Force ReBoots"),
    ("ピラニアモカシン", "Piranha Moccasins"),
    ("LT90-3", "LT-CL0WN"),
    ("アスレチックアローズ", "Athletic Arrows"),
    ("アローズ タタキベッチュー", "Arrow Pull-Ons"),
    ("アロメッシュイエロー", "Yellow-Mesh Sneakers"),
    ("アロメッシュバーミリオン", "Orange-Mesh Sneakers"),
    ("イカサシ スクランブル", "U Jellys"),
    ("ウミウシイエロー", "Neon Sea Slugs"),
    ("ウミウシパープル", "Purple Sea Slugs"),
    ("ウミウシブルー", "Blue Sea Slugs"),
    ("ウミウシボルト95", "Sea Slug Volt 95s"),
    ("ウミウシレッド", "Red Sea Slugs"),
    ("エンペーサーAg", "N-Pacer Ag"),
    ("エンペーサーAu", "N-Pacer Au"),
    ("エンペーサーCaO", "N-Pacer CaO"),
    ("オレンジアローズ", "Orange Arrows"),
    ("カナリアビーンズ", "Canary Trainers"),
    ("グッピーフラミンゴ", "Hyper Guppies"),
    ("グッピーフルブラック", "Noir Guppies"),
    ("クラゲイターAKA", "OB Gaiter Waders"),
    ("クラゲイターMIZ", "AG Gaiter Waders"),
    ("クレイジーアローズ", "Crazy Arrows"),
    ("シアンビーンズ", "Cyan Trainers"),
    ("シェルバシラWO", "Slamgerine Slip-Ons"),
    ("シャコナックル", "Blue Shrimpsiders"),
    ("スミレビーンズ", "Violet Trainers"),
    ("ピンクビーンズ", "Pink Trainers"),
    ("フカヒレニマイバ", "Mako Bucket Hi-Tops"),
    ("ブラックビーンズ", "Black Trainers"),
    ("ホワイトアローズ", "White Arrows"),
    ("MODZ-9", "E-JECT 30XX"),
    ("MODZ-9S", "E-JECT 30VV"),
    ("MOVEレッド", "Turbo Tabi Red"),
    ("キャンバス クマノミ", "Clownfish Basics"),
    ("キャンバス バナナ", "Banana Basics"),
    ("キャンバス ホワイト", "Cream Basics"),
    ("クラム600 カンロ", "Ink-Black Clam 600s"),
    ("クラム600 コハク", "White Clam 600s"),
    ("グリッチョ オレンジ", "Orange Lo-Tops"),
    ("グリッチョ グリーン 限定版", "LE Lo-Tops"),
    ("グリッチョ ブルー", "Blue Lo-Tops"),
    ("サイクルシューズ エナジー", "Stamina Cycling Shoes"),
    ("サイクルシューズ ソーダ", "Energy Cycling Shoes"),
    ("ザ・ベース ボス", "Suede Bosses"),
    ("ザ・ベース ルーキー", "Suede Basics"),
    ("シーホース イエロー", "Yellow Seahorses"),
    ("シーホース ブラックレザー", "Black Seahorses"),
    ("シーホース ホワイト", "White Seahorses"),
    ("スパイカ タタキベッチュー", "Toni Kensa Soccer Shoes"),
    ("デカロノーレース ブルー", "Blue Laceless Dakroniks"),
    ("デカロノーレース ホワイト", "White Laceless Dakroniks"),
    ("ノーリーチャッカ グレー", "Suede Gray Lace-Ups"),
    ("ノーリーチャッカ トライブ", "Suede Nation Lace-Ups"),
    ("ノーリーチャッカ ロビンズ", "Suede Marine Lace-Ups"),
    ("ヒモヒモグリーン", "Green Lace-Ups"),
    ("ベリベリホワイト", "White 3-Straps"),
    ("ベリベリレッド", "Red 3-Straps"),
    ("ボルダーシューズ タイノエ", "Sunny Climbing Shoes"),
    ("ボルダーシューズ ハザクラ", "Birch Climbing Shoes"),
    ("ユデスパイカ", "Soccer Shoes"),
    ("レアスパイカ", "LE Soccer Shoes"),
    ("NNJグリーン", "Wasabi Tabi"),
    ("スリッポン チドリ", "Squid-Stitch Slip-Ons"),
    ("スリッポン ブルー", "Blue Slip-Ons"),
    ("スリッポン ポルカ", "Polka-Dot Slip-Ons"),
    ("スリッポン レッド", "Red Slip-Ons"),
    ("チゴフグスリッポン", "ZedFry Slip-Ons"),
    ("トレッキングカスタム", "Custom Trail Boots"),
    ("トレッキングプロ", "Pro Trail Boots"),
    ("トレッキングライト", "Trail Boots"),
    ("エギング3xHF", "Shivery Squidkid III"),
    ("エギング3xMT", "Big Squidkid III"),
    ("エギング3xOU", "Fried Squidkid III"),
    ("サンモンヨウキャンバスHi", "Trifecta Hi-Tops"),
    ("サンモンヨウシャワサン", "Trifecta Sandals"),
    ("サンモンヨウダックブーツ", "Trifecta Duck Boots"),
    ("スリミクロッグ クサリ", "Chained DC Toejamz"),
    ("スリミクロッグ スタッズ", "Jeweled DC Toejamz"),
    ("スリミクロッグ マーブル", "Swirled DC Toejamz"),
    ("ヒーローブーツ レプリカ", "Hero Boot Replicas"),
    ("オーダーシューズ レプリカ", "Order Boot Replicas"),
    ("アーマーブーツ レプリカ", "Armor Boot Replicas"),
    ("アンクルサポーター", "Kick Dampeners"),
    ("イイダチスリッポン", "Marinated Slip-Ons"),
    ("イダテンヒモサン", "Knotty Bois"),
    ("エンチャントブーツ", "Enchanted Boots"),
    ("オナガノタビ", "Eel Heel Socks"),
    ("キルトローファー スゲソ", "Base Fringed Loafers"),
    ("キルトローファー ルーズ", "Baggy-Sock Fringe Loafs"),
    ("サムライシューズ", "Samurai Shoes"),
    ("シノビアシ", "Squinja Boots"),
    ("スクールローファー スゲソ", "Base School Shoes"),
    ("スクールローファー ハイソ", "School Shoes + Hi Socks"),
    ("タコティカルなすねあて", "Steel Greaves"),
    ("バーサークグリーブ", "Chaos Kicks"),
    ("パワードレッグス", "Power Boots"),
    ("パワードレッグス オリジン", "Power Boots Mk I"),
    ("ヒーローキックス レプリカ", "Hero Runner Replicas"),
    ("ヒメイトスニーカー", "Pearlescent Kicks"),
    ("ひれおくんのあし", "Fresh Fish Feet"),
    ("ホホジロノポックリ", "Faux Sharkskin Platfins"),
    ("マンダノナガグツ", "Big Muds"),
    ("カリスマシンガーブーツ", "Brinestone Boots"),
    ("ゲソバタアシスト", "Flipper Floppers"),
    ("ゾネスティックブーツ", "Octoleet Boots"),
    ("チギリノヒモ", "Friendship Bracelet"),
    ("ノックアウトシューズ", "Knockout Boots"),
    ("ノンスリップタクミ", "Nonslip Senseis"),
    ("バンカラコロン", "Wooden Sandals"),
    ("マッドラバー", "Angry Rain Boots"),
    ("ローラーシューズGT", "Trevally Derby Rollers"),
    ("AGE262", "Fry Tops"),
    ("ジャッジメントフット", "Burden of Floof"),
];

/// 日本語名からギアの公式英語名を引く。
pub fn lookup_name_en(name_ja: &str) -> Option<&'static str> {
    GEAR_NAME_EN.iter().find(|(k, _)| *k == name_ja).map(|(_, en)| *en)
}

/// ブランドの日本語名 → 公式英語名（20 ブランド、全種。うち「エゾッコリー」＝Z+F・
/// 「クマサン商会」＝Grizzco はサーモンラン報酬専用で splatoon3.ink の 18 種には無かった）。
pub const BRAND_NAME_EN: &[(&str, &str)] = &[
    ("バラズシ", "Barazushi"),
    ("ロッケンベルグ", "Rockenberg"),
    ("アタリメイド", "Cuttlegear"),
    ("アナアキ", "Annaki"),
    ("シグレニ", "Inkline"),
    ("ジモン", "Splash Mob"),
    ("アイロニック", "Zink"),
    ("ホタックス", "Skalop"),
    ("ホッコリー", "Firefin"),
    ("アロメ", "Tentatek"),
    ("タタキケンサキ", "Toni Kensa"),
    ("クラーゲス", "Krak-On"),
    ("フォーリマ", "Forge"),
    ("ヤコ", "Takoroka"),
    ("エゾッコ", "Zekko"),
    ("エンペリー", "Enperry"),
    ("バトロイカ", "SquidForce"),
    ("シチリン", "Emberz"),
    ("エゾッコリー", "Z+F"),
    ("クマサン商会", "Grizzco"),
];

/// ブランドの日本語名から公式英語名を引く。
pub fn lookup_brand_name_en(brand_ja: &str) -> Option<&'static str> {
    BRAND_NAME_EN.iter().find(|(k, _)| *k == brand_ja).map(|(_, en)| *en)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn entries_complete_and_unique() {
        let mut seen = std::collections::HashSet::new();
        for (ja, en) in GEAR_NAME_EN {
            assert!(!ja.is_empty() && !en.is_empty(), "incomplete entry: {ja}");
            assert!(seen.insert(*ja), "duplicate ja name: {ja}");
        }
        assert_eq!(GEAR_NAME_EN.len(), 833);
    }

    #[test]
    fn brand_entries_complete_and_unique() {
        let mut seen = std::collections::HashSet::new();
        for (ja, en) in BRAND_NAME_EN {
            assert!(!ja.is_empty() && !en.is_empty(), "incomplete entry: {ja}");
            assert!(seen.insert(*ja), "duplicate ja name: {ja}");
        }
        assert_eq!(BRAND_NAME_EN.len(), 20);
    }

    #[test]
    fn lookup_known_gear() {
        assert_eq!(lookup_name_en("イトヨリキャップ"), Some("Bream-Brim Cap"));
        assert_eq!(lookup_name_en("イカフィットメット"), Some("Slipstream Helmet"));
        assert_eq!(lookup_name_en("unknown"), None);
    }

    #[test]
    fn lookup_known_brand() {
        assert_eq!(lookup_brand_name_en("アロメ"), Some("Tentatek"));
        assert_eq!(lookup_brand_name_en("クマサン商会"), Some("Grizzco"));
        assert_eq!(lookup_brand_name_en("エゾッコリー"), Some("Z+F"));
        assert_eq!(lookup_brand_name_en("unknown"), None);
    }
}
