/**
 * パネルを PNG / HTML として保存する(#500 / #505)。
 *
 * 画面に出ているパネルをそのまま写すので、テーマ色や凡例は表示と一致する。
 * 表示にしかない要素(操作ボタン・長い注釈)は `EXPORT_HIDE_CLASS` を付けて除外し、
 * 書き出しにしか無い要素(絞り込み条件のキャプション)は `.is-exporting` 中だけ表示する。
 *
 * PNG は角丸の外側を透過のまま残す。HTML は単体ファイルで、散布図はホバー tip が動く。
 */
import { toPng } from 'html-to-image'
import { invoke } from '@tauri-apps/api/core'
import { getVersion } from '@tauri-apps/api/app'
import { displayVersion } from './version'

/** 画像に写したくない操作 UI に付けるクラス。 */
export const EXPORT_HIDE_CLASS = 'panel-export-hide'

/** キャプチャ中だけパネルのルートに付くクラス。CSS はこれを見てキャプションを出す。 */
const EXPORTING_CLASS = 'is-exporting'

/** PNG 保存直前にパネルへ飛ばす。散布図ツールチップの再配置などに使う。 */
export const PANEL_EXPORT_PREPARE_EVENT = 'panel-export-prepare'

/** HTML 保存直前にパネルへ飛ばす。アプリ側の固定チップを消す。 */
export const PANEL_EXPORT_HTML_PREPARE_EVENT = 'panel-export-html-prepare'

export type PanelExportFormat = 'png' | 'html'

/** アプリ版は起動中に変わらないので、一度取ったら使い回す。 */
let cachedAppVersion: string | null = null

async function appVersion(): Promise<string> {
  if (cachedAppVersion !== null) return cachedAppVersion
  try {
    cachedAppVersion = await getVersion()
  } catch {
    cachedAppVersion = ''
  }
  return cachedAppVersion
}

/** `YYYY-MM-DD`。ファイル名と同じローカル日付。 */
function formatExportDate(now = new Date()): string {
  return [
    now.getFullYear(),
    String(now.getMonth() + 1).padStart(2, '0'),
    String(now.getDate()).padStart(2, '0'),
  ].join('-')
}

/**
 * 右下クレジット。例: `Generated by SpLabo v0.9.7 · 2026-07-27`
 * 版が取れなければ版なしで出す。
 *
 * 開発ビルドでは版が常に `0.0.0-dev` で、書き出した画像がどのビルドのものか特定できない。
 * `displayVersion()` がコミット ID を添える(#569)。
 */
export function buildExportCredit(version: string, now = new Date()): string {
  const date = formatExportDate(now)
  return version
    ? `Generated by SpLabo v${displayVersion(version)} · ${date}`
    : `Generated by SpLabo · ${date}`
}

/** Windows / macOS のどちらでも使えないファイル名文字を落とす。 */
function sanitizeFilenamePart(s: string): string {
  return s
    .replace(/[\\/:*?"<>|]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

/** `splabo-環境分析-ブキ散布図-2026-07-26.png` 形式のファイル名。 */
export function buildPanelExportFilename(
  screen: string,
  panel: string,
  format: PanelExportFormat = 'png',
  now = new Date(),
): string {
  const date = formatExportDate(now)
  const parts = ['splabo', screen, panel, date].map(sanitizeFilenamePart).filter(Boolean)
  return `${parts.join('-')}.${format === 'html' ? 'html' : 'png'}`
}

/** @deprecated 互換用。`buildPanelExportFilename(..., 'png')` と同じ。 */
export function buildPanelImageFilename(screen: string, panel: string, now = new Date()): string {
  return buildPanelExportFilename(screen, panel, 'png', now)
}

function cssVar(name: string, fallback: string): string {
  const v = getComputedStyle(document.documentElement).getPropertyValue(name).trim()
  return v || fallback
}

/** `#rgb` / `#rrggbb` → `rgba(r,g,b,a)`。html-to-image 向けに半透明背景を確実に焼く。 */
function hexToRgba(hex: string, alpha: number): string | null {
  const h = hex.replace('#', '').trim()
  const full = h.length === 3 ? h.split('').map(c => c + c).join('') : h
  if (!/^[0-9a-fA-F]{6}$/.test(full)) return null
  const r = parseInt(full.slice(0, 2), 16)
  const g = parseInt(full.slice(2, 4), 16)
  const b = parseInt(full.slice(4, 6), 16)
  return `rgba(${r}, ${g}, ${b}, ${alpha})`
}

/**
 * 書き出し時にパネル幅を中身の実寸へ寄せる(#546)。
 *
 * ヒートマップ・カレンダーは列数から幅を決める**固定幅 SVG** で描いている。一方カード幅は
 * ダッシュボードのグリッドが決めるため、
 *
 * - 列が少ない … SVG 幅 < カード幅 → 画像の右に死に余白が残る
 * - 列が多い   … SVG 幅 > カード幅 → `html-to-image` はノードのボックスで
 *                ラスタライズするので、はみ出した分が画像から欠ける
 *
 * どちらもキャプチャ中だけカード幅を中身に合わせれば直る。
 *
 * 幅を数えるのは**中身なりの幅を持つ要素**、すなわち固定幅の SVG と表(#592)。
 * 環境分析のヒートマップは SVG ではなく `<table>` で描いていて、SVG だけを見ていた頃は
 * 幅を測れずに諦め、**画面上のパネル幅(＝ウィンドウ幅いっぱい)のまま**書き出していた。
 * 列が少ない軸(スペシャル × ルール等)では画像の 7 割が空白になっていた。
 *
 * キャプション・注釈は折り返す前提の文章なので数えない(1 行に伸ばすと極端に横長になる)。
 * 凡例は `flex-wrap` なので狭くても折り返す。
 *
 * Recharts のパネルは SVG 幅 = コンテナ幅なので目標幅が現在の幅と一致し、何も起きない。
 *
 * 戻り値は元のスタイルへ戻す関数(画面を汚さないため)。
 */
/**
 * 要素とその子孫の**右端**(ビューポート座標)。
 *
 * `getBoundingClientRect()` は変形後の矩形を返すので、回転した見出しのように
 * 親の箱からはみ出すものもここで拾える。親の矩形は子孫のはみ出しを含まない。
 */
/**
 * 画像に写さない要素を、レイアウトからも外す(#592)。
 *
 * PNG は `html-to-image` の `filter` で除外しているが、**キャプチャの寸法は
 * 元のノードのまま**なので、除外した要素が占めていた分が**空白として残る**。
 * 環境分析のヒートマップでは、注釈や操作ボタンの高さがそのまま画像下部の余白になっていた。
 *
 * `display: none` にすればレイアウトが詰まり、ノードの高さ自体が縮む。
 * 戻り値は元へ戻す関数。
 */
function collapseExportHidden(node: HTMLElement): () => void {
  const changed: { el: HTMLElement; display: string }[] = []
  node.querySelectorAll<HTMLElement>(`.${EXPORT_HIDE_CLASS}`).forEach(el => {
    changed.push({ el, display: el.style.display })
    el.style.display = 'none'
  })
  return () => {
    for (const c of changed) c.el.style.display = c.display
  }
}

/**
 * 書き出し中だけスクロール枠を解いて、中身を丸ごと写せるようにする(#592)。
 *
 * 環境分析のヒートマップは `.env-heatmap-wrap { overflow: auto; max-height: 70vh }` の
 * 中にある。画面では正しい（大きい表でも画面内に収まる）が、そのまま書き出すと
 *
 * - **スクロールバーが画像に写り込む**
 * - 枠からはみ出した行が**途中で切れる**（全部は写らない）
 * - 枠の高さが残るので、幅を詰めたあと**下に余白が空く**
 *
 * 画像は紙と同じでスクロールできない。中身を全部見せるのが正しい。
 *
 * 幅を測る前に呼ぶこと（切られたままの幅を測らないため）。
 * 戻り値は元へ戻す関数。
 */
function expandScrollAreas(node: HTMLElement): () => void {
  const changed: { el: HTMLElement; overflow: string; maxH: string; maxW: string }[] = []
  node.querySelectorAll<HTMLElement>('*').forEach(el => {
    const cs = getComputedStyle(el)
    const scrolls = /auto|scroll/.test(cs.overflowX) || /auto|scroll/.test(cs.overflowY)
    const capped = cs.maxHeight !== 'none'
    if (!scrolls && !capped) return
    changed.push({ el, overflow: el.style.overflow, maxH: el.style.maxHeight, maxW: el.style.maxWidth })
    el.style.overflow = 'visible'
    el.style.maxHeight = 'none'
    // 枠が親幅に縛られていると、パネルを中身幅へ寄せるときに追随できない。
    el.style.maxWidth = 'none'
  })
  return () => {
    for (const c of changed) {
      c.el.style.overflow = c.overflow
      c.el.style.maxHeight = c.maxH
      c.el.style.maxWidth = c.maxW
    }
  }
}

function contentRight(el: Element): number {
  let right = el.getBoundingClientRect().right
  el.querySelectorAll('*').forEach(child => {
    const r = child.getBoundingClientRect()
    // 非表示要素は 0 幅 0 位置で返るので数えない。
    if (r.width > 0 && r.right > right) right = r.right
  })
  return right
}

function fitExportWidth(node: HTMLElement): () => void {
  const noop = () => {}
  const cs = getComputedStyle(node)
  const frameX =
    parseFloat(cs.paddingLeft) + parseFloat(cs.paddingRight) +
    parseFloat(cs.borderLeftWidth) + parseFloat(cs.borderRightWidth)
  if (!Number.isFinite(frameX)) return noop

  let contentW = 0
  node.querySelectorAll('svg, table').forEach(el => {
    // 画像に写らない操作 UI のアイコンは数えない。
    if (el.closest(`.${EXPORT_HIDE_CLASS}`)) return
    let w = el.getBoundingClientRect().width
    // ヒートマップの斜め列ラベルのように、**宣言サイズの外へ描かれる**要素がある
    // (`.chart-card svg { overflow: visible }` なので画面では見えている)。
    // 宣言幅だけで詰めると、はみ出していた分が画像の端で切れる(#552)。
    // getBBox() は子要素の実際の描画範囲を返すので、そちらも見て広い方を採る。
    // 表には getBBox が無いので SVG のときだけ見る。
    if (el instanceof SVGGraphicsElement) {
      try {
        const bb = el.getBBox()
        if (bb.width > 0) w = Math.max(w, bb.x + bb.width)
      } catch {
        // 未レンダリング(display:none 等)の SVG では getBBox が投げる。宣言幅で足りる。
      }
    } else {
      // 表も同じ問題を持つ。環境分析ヒートマップの斜め列見出しは
      // `transform: rotate(-45deg)` で**表の箱の外へ**出るが、
      // 表の矩形にはその分が入らない。詰めると右端のラベルが切れる(#552 と同じ壊れ方)。
      // 変形後の矩形は getBoundingClientRect が返すので、子孫の右端まで見て広い方を採る。
      w = Math.max(w, contentRight(el) - el.getBoundingClientRect().left)
    }
    if (w > contentW) contentW = w
  })
  if (contentW <= 0) return noop

  const target = Math.max(Math.ceil(contentW + frameX), MIN_EXPORT_WIDTH)
  const current = Math.round(node.getBoundingClientRect().width)
  if (Math.abs(target - current) <= 1) return noop

  const prev = {
    width:    node.style.width,
    minWidth: node.style.minWidth,
    maxWidth: node.style.maxWidth,
  }
  node.style.width    = `${target}px`
  node.style.minWidth = `${target}px`
  node.style.maxWidth = `${target}px`
  return () => {
    node.style.width    = prev.width
    node.style.minWidth = prev.minWidth
    node.style.maxWidth = prev.maxWidth
  }
}

/**
 * 書き出し幅の下限(px)。ダッシュボードの基準トラック幅に合わせる。
 * これより狭めると、タイトルが右上ロゴ用に確保した 140px と競って窮屈になる。
 */
const MIN_EXPORT_WIDTH = 420

/** レイアウト変更(キャプション表示)が反映されてから描画するために 2 フレーム待つ。 */
function nextFrames(): Promise<void> {
  return new Promise(resolve => {
    requestAnimationFrame(() => requestAnimationFrame(() => resolve()))
  })
}

async function invokeSave(
  filename: string,
  dataBase64: string,
  format: PanelExportFormat,
): Promise<string | null> {
  return await invoke<string | null>('save_panel_image', {
    filename,
    dataBase64,
    format,
  })
}

function fillExportCredit(node: HTMLElement, credit: string): void {
  node.querySelectorAll('.panel-export-credit').forEach(el => {
    el.textContent = credit
  })
}

/**
 * パネルを PNG にして保存ダイアログへ渡す。
 * 戻り値は保存先パス。キャンセルされたら null。
 */
export async function savePanelAsPng(node: HTMLElement, screen: string, panel: string): Promise<string | null> {
  node.classList.add(EXPORTING_CLASS)
  const tooltipBgs: { el: HTMLElement; prev: string }[] = []
  let uncollapse: (() => void) | null = null
  let unexpand: (() => void) | null = null
  let unfit: (() => void) | null = null
  try {
    // 保存した瞬間の版・日付を焼き込む(画面に出しっぱなしの古い日付にしない)。
    fillExportCredit(node, buildExportCredit(await appVersion()))
    // 写さない要素をレイアウトからも外す(#592)。残すと下に空白が出る。
    uncollapse = collapseExportHidden(node)
    // スクロール枠を解いて中身を全部出す(#592)。**幅を測る前に**やる。
    unexpand = expandScrollAreas(node)
    // 固定幅 SVG のパネルで右に余白が出る / はみ出しが欠けるのを防ぐ(#546)。
    // ツールチップの載せ替えより先に効かせる(位置計算が新しい幅を見るように)。
    unfit = fitExportWidth(node)
    await nextFrames()
    // ツールチップ背景を rgba 半透明に(color-mix はラスタライズで落ちることがある)。
    const tipBg = hexToRgba(cssVar('--surface', '#17172a'), 0.72)
      ?? 'rgba(23, 23, 42, 0.72)'
    node.querySelectorAll<HTMLElement>('.cal-tooltip').forEach(el => {
      tooltipBgs.push({ el, prev: el.style.background })
      el.style.background = tipBg
    })
    // 散布図ツールチップを「他ドットを避ける位置」へ載せ替える(リスナ側で flushSync)。
    node.dispatchEvent(new CustomEvent(PANEL_EXPORT_PREPARE_EVENT, { bubbles: false }))
    await nextFrames()
    // backgroundColor を指定しない → 角丸の外側は透明。パネル内は要素自身の背景色。
    const dataUrl = await toPng(node, {
      // 等倍だと軸ラベルがつぶれる。2 倍なら 420px 幅のカードでも十分読める。
      pixelRatio: 2,
      // 既定では index.html が読む Google Fonts を毎回ダウンロードして埋め込もうとする。
      // パネル内は system-ui 系しか使っておらず、オフラインでは失敗するだけなので飛ばす。
      skipFonts: true,
      filter: (el) => !(el instanceof Element) || !el.classList.contains(EXPORT_HIDE_CLASS),
    })
    const dataBase64 = dataUrl.slice(dataUrl.indexOf(',') + 1)
    return await invokeSave(buildPanelExportFilename(screen, panel, 'png'), dataBase64, 'png')
  } finally {
    tooltipBgs.forEach(({ el, prev }) => { el.style.background = prev })
    unfit?.()
    unexpand?.()
    uncollapse?.()
    node.classList.remove(EXPORTING_CLASS)
  }
}

// ---------------------------------------------------------------------------
// HTML 単体書き出し(#505)
// ---------------------------------------------------------------------------

/** 単体 HTML に同梱するスタイルシートから拾うセレクタ接頭辞。 */
const HTML_CSS_PREFIXES = [
  '.chart-card',
  '.chart-hover',
  '.custom-chart',
  '.env-chart',
  '.env-hm',
  '.cal-',
  '.cal-tooltip',
  '.scatter-',
  '.panel-export',
  '.is-exporting',
  '.recharts-',
  '.hover-tt',
  '.heatmap',
  '.hm-',
  '.line-chart',
]

function collectRootCssVariables(): string {
  const style = getComputedStyle(document.documentElement)
  const decls: string[] = []
  for (let i = 0; i < style.length; i++) {
    const name = style.item(i)
    if (!name.startsWith('--')) continue
    const value = style.getPropertyValue(name).trim()
    if (value) decls.push(`${name}: ${value};`)
  }
  return decls.length ? `:root {\n  ${decls.join('\n  ')}\n}` : ''
}

function selectorMatchesExport(selectorText: string): boolean {
  return HTML_CSS_PREFIXES.some(prefix => selectorText.includes(prefix))
}

function collectExportStylesheets(): string {
  const chunks: string[] = []
  for (const sheet of Array.from(document.styleSheets)) {
    let rules: CSSRuleList
    try {
      rules = sheet.cssRules
    } catch {
      // 外部オリジン等は読めない。テーマ変数は :root 側で足りる想定。
      continue
    }
    for (const rule of Array.from(rules)) {
      if (rule instanceof CSSStyleRule) {
        if (selectorMatchesExport(rule.selectorText)) chunks.push(rule.cssText)
      } else if (rule instanceof CSSMediaRule) {
        const inner: string[] = []
        for (const sub of Array.from(rule.cssRules)) {
          if (sub instanceof CSSStyleRule && selectorMatchesExport(sub.selectorText)) {
            inner.push(sub.cssText)
          }
        }
        if (inner.length) chunks.push(`@media ${rule.media.mediaText} {\n${inner.join('\n')}\n}`)
      } else if (rule instanceof CSSSupportsRule) {
        const inner: string[] = []
        for (const sub of Array.from(rule.cssRules)) {
          if (sub instanceof CSSStyleRule && selectorMatchesExport(sub.selectorText)) {
            inner.push(sub.cssText)
          }
        }
        if (inner.length) chunks.push(`@supports ${rule.conditionText} {\n${inner.join('\n')}\n}`)
      } else if (rule instanceof CSSKeyframesRule) {
        if (rule.name.includes('panel-export') || rule.name.includes('recharts')) {
          chunks.push(rule.cssText)
        }
      }
    }
  }
  return chunks.join('\n')
}

async function urlToDataUri(src: string): Promise<string> {
  if (!src || src.startsWith('data:')) return src
  try {
    const res = await fetch(src)
    if (!res.ok) return src
    const blob = await res.blob()
    return await new Promise<string>((resolve, reject) => {
      const reader = new FileReader()
      reader.onload = () => resolve(String(reader.result))
      reader.onerror = () => reject(reader.error ?? new Error('FileReader failed'))
      reader.readAsDataURL(blob)
    })
  } catch {
    return src
  }
}

async function inlineImages(root: HTMLElement): Promise<void> {
  const imgs = Array.from(root.querySelectorAll('img'))
  await Promise.all(imgs.map(async (img) => {
    const src = img.getAttribute('src')
    if (!src) return
    const data = await urlToDataUri(src)
    img.setAttribute('src', data)
  }))
}

/** HTML 埋め込み用の追加 CSS(アプリ CSS に無い固定レイアウト)。 */
const HTML_EXPORT_EXTRA_CSS = `
/* App.css のグローバルリセットはセレクタ収集から漏れるのでここで補う。
   box-sizing が content-box だと padding 分だけ枠とグラフ幅がずれる。 */
*, *::before, *::after { box-sizing: border-box; }
html, body {
  margin: 0;
  padding: 16px;
  background: var(--bg, #0f0f1a);
  color: var(--text, #eee);
  font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
}
/* キャプチャ時の実寸を保つ。max-width で縮めると SVG 固定幅と枠がずれる。 */
body > .chart-card,
body > .env-chart-section {
  margin: 0 auto;
  flex-shrink: 0;
}
/* グリッド用の span 指定は単体 HTML では意味が無く、稀に幅計算を乱すので無効化。 */
body > .chart-card.chart-card--wide,
body > .chart-card.chart-card--full {
  grid-column: auto;
}
#splabo-export-tip {
  display: none;
  position: fixed;
  z-index: 9999;
  pointer-events: none;
  min-width: 160px;
  max-width: 280px;
  background: color-mix(in srgb, var(--surface) 88%, transparent);
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.35);
}
#splabo-export-tip.is-visible { display: block; }
#splabo-export-tip .hover-tt-title {
  display: flex;
  align-items: center;
  gap: 6px;
  font-weight: 600;
  margin-bottom: 4px;
}
#splabo-export-tip .hover-tt-icon {
  height: 36px;
  width: auto;
  max-width: 72px;
  object-fit: contain;
}
#splabo-export-tip .hover-tt-kit {
  display: flex;
  align-items: center;
  gap: 6px;
  margin: 2px 0 6px;
  padding-left: 42px;
}
#splabo-export-tip .hover-tt-kit-well {
  display: flex;
  align-items: center;
  gap: 6px;
  width: fit-content;
  background: #17172a;
  border-radius: 4px;
  padding: 3px 6px;
}
#splabo-export-tip .hover-tt-kit-icon {
  height: 14px;
  width: auto;
  max-width: 22px;
  object-fit: contain;
}
#splabo-export-tip .hover-tt-kit-icon--sp {
  height: 16px;
  max-width: 24px;
}
[data-scatter-point="true"] { cursor: pointer; }
`

/** 散布図ホバー用(オフライン・CDN なし)。 */
const HTML_EXPORT_TIP_SCRIPT = `(function () {
  var tip = document.getElementById('splabo-export-tip');
  if (!tip) return;
  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }
  function render(payload) {
    if (!payload) return '';
    if (payload.kind === 'group') {
      var html = '<div class="hover-tt-title">' + esc(payload.groupTitle) + '</div>';
      (payload.members || []).forEach(function (m) {
        html += '<div class="hover-tt-row hover-tt-row--muted">' + esc(m) + '</div>';
      });
      if (payload.more > 0) {
        html += '<div class="hover-tt-row hover-tt-row--muted">他 ' + esc(payload.more) + ' 件</div>';
      }
      return html;
    }
    var icon = payload.iconUrl
      ? '<img class="hover-tt-icon" src="' + esc(payload.iconUrl) + '" alt="">'
      : '';
    var out = '<div class="hover-tt-title">' + icon + esc(payload.name) + '</div>';
    if (payload.spIconUrl || payload.subIconUrl) {
      out += '<div class="hover-tt-kit"><div class="hover-tt-kit-well">';
      if (payload.spIconUrl) {
        out += '<img class="hover-tt-kit-icon hover-tt-kit-icon--sp" src="' + esc(payload.spIconUrl) + '" alt="" title="' + esc(payload.spName) + '">';
      }
      if (payload.subIconUrl) {
        out += '<img class="hover-tt-kit-icon" src="' + esc(payload.subIconUrl) + '" alt="" title="' + esc(payload.subName) + '">';
      }
      out += '</div></div>';
    }
    (payload.rows || []).forEach(function (r) {
      var cls = r.muted ? 'hover-tt-row hover-tt-row--muted' : 'hover-tt-row';
      out += '<div class="' + cls + '">' + esc(r.label) + ': ' + esc(r.value) + '</div>';
    });
    return out;
  }
  function place(ev) {
    var pad = 12;
    var tw = tip.offsetWidth || 180;
    var th = tip.offsetHeight || 80;
    var left = ev.clientX + pad;
    var top = ev.clientY + pad;
    if (left + tw > window.innerWidth - 8) left = ev.clientX - tw - pad;
    if (top + th > window.innerHeight - 8) top = ev.clientY - th - pad;
    tip.style.left = Math.max(8, left) + 'px';
    tip.style.top = Math.max(8, top) + 'px';
  }
  function show(ev, el) {
    var raw = el.getAttribute('data-scatter-tip');
    if (!raw) return;
    var payload;
    try { payload = JSON.parse(raw); } catch (e) { return; }
    tip.innerHTML = render(payload);
    tip.classList.add('is-visible');
    place(ev);
  }
  function hide() {
    tip.classList.remove('is-visible');
    tip.innerHTML = '';
  }
  // ── レンズ（ブキ画像の散布図・#630）──────────────────────────────
  //
  // アプリと同じ「カーソルに近いアイコン同士が反発する」を、保存した HTML でも動かす。
  // React は無いので、DOM から元の座標を読んで transform を直接書く。
  //
  // 🔴 数値はアプリ側（ScatterChart.tsx の LENS_*）と揃えること。片方だけ変えると
  // 画面と保存物で挙動が違う。
  var LENS_R = 130, LENS_FALLOFF = 3, LENS_PULL = 0.10, LENS_ITER = 60;

  /** 画像の点を持つチャートだけレンズを付ける。持たない（丸の）チャートは従来どおり。 */
  function setupLens(area) {
    var svg = area.querySelector('svg');
    if (!svg) return false;
    var nodes = [];
    area.querySelectorAll('[data-scatter-point="true"]').forEach(function (el) {
      var img = el.querySelector('image');
      if (!img) return;
      var w = parseFloat(img.getAttribute('width'));
      if (!(w > 0)) return;
      nodes.push({
        el: el,
        mover: img.parentNode,
        size: w,
        bx: parseFloat(img.getAttribute('x')) + w / 2,
        by: parseFloat(img.getAttribute('y')) + w / 2,
        w: 0, x: 0, y: 0
      });
    });
    if (nodes.length < 2) return false;
    var span = nodes[0].size;

    // 収める範囲は「点が元から居る矩形」。アプリ側と同じ考え方。
    var lo = { x: Infinity, y: Infinity }, hi = { x: -Infinity, y: -Infinity };
    nodes.forEach(function (n) {
      if (n.bx < lo.x) lo.x = n.bx;
      if (n.by < lo.y) lo.y = n.by;
      if (n.bx > hi.x) hi.x = n.bx;
      if (n.by > hi.y) hi.y = n.by;
    });
    function cl(v, a, b) { return v < a ? a : (v > b ? b : v); }
    function rest(n) { n.mover.style.transform = 'translate(0px, 0px)'; }

    area.addEventListener('mouseleave', function () {
      nodes.forEach(rest);
      hide();
    });
    area.addEventListener('mousemove', function (ev) {
      var r = svg.getBoundingClientRect();
      var cx = ev.clientX - r.left, cy = ev.clientY - r.top;

      var moving = [], fixed = [];
      nodes.forEach(function (n) {
        var d = Math.hypot(n.bx - cx, n.by - cy);
        if (d >= LENS_R) {
          rest(n);
          if (d < LENS_R + span * 2) fixed.push(n);
          return;
        }
        n.w = Math.pow(1 - d / LENS_R, LENS_FALLOFF);
        n.x = n.bx; n.y = n.by;
        moving.push(n);
      });

      for (var it = 0; it < LENS_ITER; it++) {
        for (var a = 0; a < moving.length; a++) {
          var m = moving[a];
          m.x += (m.bx - m.x) * LENS_PULL;
          m.y += (m.by - m.y) * LENS_PULL;
        }
        for (var i = 0; i < moving.length; i++) {
          for (var j = i + 1; j < moving.length; j++) {
            var p = moving[i], q = moving[j];
            var dx = q.x - p.x, dy = q.y - p.y;
            var dist = Math.hypot(dx, dy);
            if (dist >= span) continue;
            if (dist < 1e-6) { var ang = i * 2.399963; dx = Math.cos(ang); dy = Math.sin(ang); dist = 1; }
            var push = ((span - dist) / 2) * ((p.w + q.w) / 2);
            p.x -= (dx / dist) * push; p.y -= (dy / dist) * push;
            q.x += (dx / dist) * push; q.y += (dy / dist) * push;
          }
        }
        for (var k = 0; k < moving.length; k++) {
          var mm = moving[k];
          for (var f = 0; f < fixed.length; f++) {
            var o = fixed[f];
            var ox = mm.x - o.bx, oy = mm.y - o.by;
            var od = Math.hypot(ox, oy);
            if (od >= span) continue;
            if (od < 1e-6) { ox = 1; oy = 0; od = 1; }
            var opush = (span - od) * mm.w;
            mm.x += (ox / od) * opush; mm.y += (oy / od) * opush;
          }
          mm.x = cl(mm.x, lo.x, hi.x);
          mm.y = cl(mm.y, lo.y, hi.y);
        }
      }

      // ずらした先でカーソルの下にある点をチップの対象にする。
      var near = null, nd = span / 2;
      moving.forEach(function (n) {
        n.mover.style.transform = 'translate(' + (n.x - n.bx) + 'px, ' + (n.y - n.by) + 'px)';
        var d = Math.hypot(n.x - cx, n.y - cy);
        if (d <= nd) { nd = d; near = n; }
      });
      if (near) show(ev, near.el); else hide();
      if (tip.classList.contains('is-visible')) place(ev);
    });
    return true;
  }

  var lensed = [];
  document.querySelectorAll('.chart-hover-area').forEach(function (area) {
    if (setupLens(area)) lensed.push(area);
  });

  // レンズを付けなかったチャート（丸の散布図）は、点ごとのホバーで従来どおり。
  document.querySelectorAll('[data-scatter-point="true"]').forEach(function (el) {
    for (var i = 0; i < lensed.length; i++) if (lensed[i].contains(el)) return;
    el.addEventListener('mouseenter', function (ev) { show(ev, el); });
    el.addEventListener('mousemove', function (ev) {
      if (tip.classList.contains('is-visible')) place(ev);
    });
    el.addEventListener('mouseleave', hide);
  });
})();`

function utf8ToBase64(text: string): string {
  const bytes = new TextEncoder().encode(text)
  let binary = ''
  const chunk = 0x8000
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunk))
  }
  return btoa(binary)
}

function buildStandaloneHtml(panelHtml: string, title: string): string {
  const css = [
    collectRootCssVariables(),
    collectExportStylesheets(),
    HTML_EXPORT_EXTRA_CSS,
  ].filter(Boolean).join('\n\n')

  return `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<style>
${css}
</style>
</head>
<body>
${panelHtml}
<div id="splabo-export-tip" class="cal-tooltip" aria-hidden="true"></div>
<script>
${HTML_EXPORT_TIP_SCRIPT}
</script>
</body>
</html>
`
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/**
 * Recharts の ResponsiveContainer が付けた実寸をインラインで固定する。
 * HTML 単体では ResizeObserver が動かない/親幅が変わると、枠だけ縮んで SVG がはみ出す。
 * 戻り値は元スタイルへ戻す関数(アプリ画面を汚さないため)。
 */
function freezeChartGeometry(root: HTMLElement): () => void {
  const restorers: Array<() => void> = []

  const freezeBox = (el: Element) => {
    if (!(el instanceof HTMLElement) && !(el instanceof SVGElement)) return
    const rect = el.getBoundingClientRect()
    const w = Math.round(rect.width)
    const h = Math.round(rect.height)
    if (w <= 0 || h <= 0) return

    if (el instanceof SVGSVGElement) {
      const prevW = el.getAttribute('width')
      const prevH = el.getAttribute('height')
      const prevStyleW = el.style.width
      const prevStyleH = el.style.height
      el.setAttribute('width', String(w))
      el.setAttribute('height', String(h))
      el.style.width = `${w}px`
      el.style.height = `${h}px`
      restorers.push(() => {
        if (prevW == null) el.removeAttribute('width')
        else el.setAttribute('width', prevW)
        if (prevH == null) el.removeAttribute('height')
        else el.setAttribute('height', prevH)
        el.style.width = prevStyleW
        el.style.height = prevStyleH
      })
      return
    }

    if (!(el instanceof HTMLElement)) return
    const prevW = el.style.width
    const prevH = el.style.height
    const prevMinW = el.style.minWidth
    const prevMaxW = el.style.maxWidth
    el.style.width = `${w}px`
    el.style.height = `${h}px`
    el.style.minWidth = `${w}px`
    el.style.maxWidth = `${w}px`
    restorers.push(() => {
      el.style.width = prevW
      el.style.height = prevH
      el.style.minWidth = prevMinW
      el.style.maxWidth = prevMaxW
    })
  }

  freezeBox(root)
  root.querySelectorAll(
    '.chart-hover-area, .recharts-responsive-container, .recharts-wrapper, svg.recharts-surface',
  ).forEach(freezeBox)

  return () => {
    for (let i = restorers.length - 1; i >= 0; i--) restorers[i]()
  }
}

/**
 * パネルを単体 HTML にして保存ダイアログへ渡す。
 * 戻り値は保存先パス。キャンセルされたら null。
 */
export async function savePanelAsHtml(node: HTMLElement, screen: string, panel: string): Promise<string | null> {
  node.classList.add(EXPORTING_CLASS)
  let unfreeze: (() => void) | null = null
  let unexpand: (() => void) | null = null
  let unfit: (() => void) | null = null
  try {
    fillExportCredit(node, buildExportCredit(await appVersion()))
    // スクロール枠を解いて中身を全部出す(#592)。**幅を測る前に**やる。
    unexpand = expandScrollAreas(node)
    // 実寸を固める前に幅を中身へ寄せる(#546)。順序を逆にすると広いままの幅が固定される。
    unfit = fitExportWidth(node)
    node.dispatchEvent(new CustomEvent(PANEL_EXPORT_HTML_PREPARE_EVENT, { bubbles: false }))
    // キャプション表示後に ResponsiveContainer が再計測するのを待つ。
    await nextFrames()
    await nextFrames()

    // クローン前に実寸をインライン化してから clone する(構造が一致する)。
    unfreeze = freezeChartGeometry(node)

    const clone = node.cloneNode(true) as HTMLElement
    clone.querySelectorAll(`.${EXPORT_HIDE_CLASS}`).forEach(el => el.remove())
    // アプリ側で残っていた固定ツールチップは HTML では使わない。
    clone.querySelectorAll('.cal-tooltip').forEach(el => el.remove())
    // アクティブ強調はホバー前の見た目に戻す。
    clone.querySelectorAll('[data-scatter-active]').forEach(el => el.removeAttribute('data-scatter-active'))

    await inlineImages(clone)

    clone.style.boxSizing = 'border-box'

    const title = `SpLabo - ${screen} - ${panel}`
    const html = buildStandaloneHtml(clone.outerHTML, title)
    return await invokeSave(
      buildPanelExportFilename(screen, panel, 'html'),
      utf8ToBase64(html),
      'html',
    )
  } finally {
    unfreeze?.()
    unfit?.()
    unexpand?.()
    node.classList.remove(EXPORTING_CLASS)
  }
}

/** 形式を選んで保存する。 */
export async function savePanel(
  node: HTMLElement,
  screen: string,
  panel: string,
  format: PanelExportFormat,
): Promise<string | null> {
  return format === 'html'
    ? savePanelAsHtml(node, screen, panel)
    : savePanelAsPng(node, screen, panel)
}
