services:
  nxapi:
    build: .
    working_dir: /data
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Tokyo
      - NXAPI_DATA_PATH=/data
      - NXAPI_ENABLE_REMOTE_CONFIG=0
      - NXAPI_SPLATNET3_UPGRADE_QUERIES=1
